### ISSUE TITLE
Test Plan

### ISSUE THREAD

**Issue by SummerSun** [microsoft/vscode-java-dependency#10]
### Basic
- [ ] Can create java project from navigation command bar following the instructions
- [ ] Can not create java projects with conflicts name in same location
- [ ] Can press F5 to run the java project
- [ ] Can set breakpoints to debug the java project
- [ ] Can view all dependencies of the opened java project

### Simple project
- Open the project under $repo/test/simple
- [ ] Can create java project from navigation command bar following the instructions
- [ ] Can show the package of the source code 
- [ ] Can open source file  
- [ ] Can show the external "JRE System Library"
- [ ] Can show the jar under the libarary
- [ ] Can show the package under the jar
- [ ] Can show the classfile under the package and open the classfile 
- [ ] Can show the symbols in the explorers 

### Maven project
- Open the project under $repo/test/maven
- [ ] Can create java project from navigation command bar following the instructions
- [ ] Can show the package of the source code 
- [ ] Can open source file  
- [ ] Can show the external "Maven dependencies"
- [ ] Can show the jar under the libarary
- [ ] Can show the package under the jar
- [ ] Can show the classfile under the package and open the classfile 
- [ ] Can show the symbols in the explorers 

### Gradle project
- Open the project under $repo/test/gradle
- [ ] Can create java project from navigation command bar following the instructions
- [ ] Can show the package of the source code 
- [ ] Can open source file  
- [ ] Can show the external "Project and External Dependencies"
- [ ] Can show the jar under the libarary
- [ ] Can show the package under the jar
- [ ] Can show the classfile under the package and open the classfile 
- [ ] Can show the symbols in the explorers 

### Multiple project
- Open the project under $repo/test/multiple
- Should have correct behavior for both projects in the following scenarios:
- [ ] Can create java project from navigation command bar following the instructions
- [ ] Can show the package of the source code 
- [ ] Can open source file  
- [ ] Can show the external "JRE System Library"
- [ ] Can show the jar under the libarary
- [ ] Can show the package under the jar
- [ ] Can show the classfile under the package and open the classfile 
- [ ] Can show the symbols in the explorers

**Comment by lxhmavis** [comment]
### Symlink Folder

1. Create a symlink folder
   Linux/Mac
     `ln -s <SourceFolder> <ShareFolder Location>`
   Win
     `Mklink /D <ShareFolder Loaction> <SourceFolder>`
2. F1, create a java project, and select the symlink folder as the location
3. Verify the java packages explore in the JAVA DEPENDENCIES

**Comment by EricZhangzf** [comment]
### Auto Refresh
1. Create a java project from navigation command bar;
2. Open App.java, make some changes, for example: add a Test() method to the code.
3. Verify can auto refresh changes in dependency views.
