### ISSUE TITLE
The link can open in the page but the left bar can't open for JDK classes

### ISSUE THREAD

**Issue by lxhmavis** [Microsoft/vscode-java-dependency#110]
OS: Windows&&Mac
Configurations: Vscode1.29.1&&JDK1.8.0

When I open the link of the class with CTRL-Click, the link can open in the page but the left bar can't open.
![image](https://user-images.githubusercontent.com/41565966/48603804-a6ff4d80-e9b2-11e8-8eec-699e6d4cefd5.png)

**Comment by andxu** [comment]
https://github.com/Microsoft/vscode-java-dependency/issues/110
