### ISSUE TITLE
It will pop errors when open the libraries in Multiple-project

### ISSUE THREAD

**Issue by lxhmavis** [Microsoft/vscode-java-dependency#111]
OS: Windows
Configurations: VScode1.29.1&&JDK1.8.0_191

The Libraries in multiple-project, when I open the second and the third one, It will pop the errors.
![image](https://user-images.githubusercontent.com/41565966/48604232-217c9d00-e9b4-11e8-8b40-6edc8a5ad27a.png)

**Comment by Flanker32** [comment]
@lxhmavis  Could you please offer more detail infos to reproduce this issue? Like the JDK infos and logs of language server. I open the workspace in `../vscode-java-dependency/test/multiple/multiple-project.code-workspace` and visit all the Libraries and it works well.

**Comment by lxhmavis** [comment]
The bug couldn't be reproduced in the Windows and Mac with daily-build 55, so I closed it after communicating.
