### ISSUE TITLE
The current page will be replaced with the .class file.

### ISSUE THREAD

**Issue by lxhmavis** [Microsoft/vscode-java-dependency#112]
OS: Windows
Configurations: VScode1.29.1&&JDK1.8.0_191

Reproduce steps:

1. Open the java file from the package of the source code in the dependency explore.

![image](https://user-images.githubusercontent.com/41565966/48604716-aae09f00-e9b5-11e8-8826-b40cf3267ec9.png)

2. When I link string, the current page will be replaced with the String.calss

![image](https://user-images.githubusercontent.com/41565966/48604724-b6cc6100-e9b5-11e8-9367-eb6b89496b22.png)

But when I open the one from the project explore.
![image](https://user-images.githubusercontent.com/41565966/48604866-27737d80-e9b6-11e8-9bed-56a3e644ab4a.png)

**Comment by jdneo** [comment]
This is VS Code behavior. To pin the current editor in the editor bar. Simply right-click the editor title and select `Keep Open`.

![image](https://user-images.githubusercontent.com/6193897/49000289-0cfa8a80-f194-11e8-8e46-8f7ad424597f.png)
