### ISSUE TITLE
can I open .class file in dependencies explore by name

### ISSUE THREAD

**Issue by demanLiu** [Microsoft/vscode-java-dependency#115]
I want to search or find some .class file in java dependencies explore by file name, can it support?

**Comment by yaohaizh** [comment]
You can search symbols class in the command line (Ctrl + P) with `#`prefix and search the class even without the java dependency but need java language server. 
![untitled](https://user-images.githubusercontent.com/17268517/48839987-444ded80-edc8-11e8-816e-bb24860267de.png)

**Comment by demanLiu** [comment]
@yaohaizh  3q
