### ISSUE TITLE
Java-SE 10 is no longer supported

### ISSUE THREAD

**Issue by zxsn** [Microsoft/vscode-java-dependency#121]
I hope to support Java-SE 11。
warning：[build path specifies execution environment JavaSE-10,There are no JREs installed in the workspace that are strictly compatible with this environment.]

**Comment by andxu** [comment]
Surely we will add support of java 11.

**Comment by franck-schmidlin** [comment]
sorry - am right thinking this is still open? I have a similar warning message on my java 11 project
`{
	"resource": "/C:/_workspaces/frog/driving-licence-uk/",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "0",
	"severity": 4,
	"message": "Build path specifies execution environment JavaSE-10. There are no JREs installed in the workspace that are strictly compatible with this environment. ",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}`

**Comment by yaohaizh** [comment]
Fixed for Java11
