### ISSUE TITLE
[feature request] - dependency tree

### ISSUE THREAD

**Issue by fssrepository** [microsoft/vscode-java-dependency#122]
I have raised an issue on 
https://github.com/Microsoft/vscode-maven/issues/161

there was a discussion also on https://github.com/Microsoft/vscode-maven/issues/126

I'm not a big designer, but that's what I need, and struggling with on daily basis.

Pls. notice there is  "tag" button in the search bar, which changes the view between tasks and dependencies or classes. Eclipse and Netbeans has a feature to filter inside a dependency tree. It's a deal breaker for me to resolve the messy dependency tree. Unfortunately, it's a little bit much on that tiny area. Netbeans has an awful and very slow visual graph solution only, which is not that usable. For gradle also.

![image](https://user-images.githubusercontent.com/45578746/49566803-2fc33680-f92c-11e8-949e-2533b4cb2276.png)

The vscode java dependency plugin shows classes inside not showing transitive dependencies. Most of the company sucks on it, and waste the majority of the time to resolve circular dependencies, or excluding older versions as somehow it hasn't been excluded automatically.

Good common examples (official documents urges to do that):

mysql
```
<dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-spatial</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>postgresql</artifactId>
                    <groupId>postgresql</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```
jetty
```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by jdneo** [comment]
Thanks for your feedback. While, unfortunately, the dependency viewer does not have the ability to show the transitive dependencies (as far as I know). The dependencies has been flattened when at the Language Server side.

To show the dependency graph, it should be provided by the build tool's own extension. e.g. VS Code Maven has already provided a dependency graph in a text format: https://github.com/microsoft/vscode-maven/issues/161
