### ISSUE TITLE
Consider to make the nodes in the dependency tree sortable

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-dependency#123]
![sort](https://user-images.githubusercontent.com/41565966/48468649-7048fc00-e827-11e8-9260-c84208253f93.png)

The list order here is the order of occurrence in the class, which is a kind of valid order.

In **IntelliJ**, it provides two ways to sort:
- Sort by visibility
- Sort by Alphabetically

In **Eclipse**, The order is:
- Static class
- Static fields
- Static methods
- Fields
- Methods

Each part is sorted alphabetically.

We need to consider to provide the sort option to users, and what kind of sort option is provided

**Comment by jdneo** [comment]
Related issue in VS Code repo: https://github.com/Microsoft/vscode/issues/52202

**Comment by andxu** [comment]
we should have options for different sorts.

**Comment by jdneo** [comment]
Code symbols are now provided by the Outline view, which by default support several ways of sorting:

![image](https://user-images.githubusercontent.com/6193897/144179084-690f87d2-7579-42bf-883d-8c7b44f9c0d7.png)

It should fulfill the original request.
