### ISSUE TITLE
The empty package can't display

### ISSUE THREAD

**Issue by lxhmavis** [microsoft/vscode-java-dependency#126]
**### Configuration:**
```
Vscode: 1.29.1
JDK: 1.8.0_191
OS: Win/Mac
Build: 60
```
The empty package can't display in the dependency view, as below:

![image](https://user-images.githubusercontent.com/41565966/49785717-62ba5f80-fd5c-11e8-97f3-6bdfbfde9005.png)

**Comment by andxu** [comment]
By design if no java classes or resource files are under default package. @Flanker32 to double confirm for that.

**Comment by jdneo** [comment]
We should show those empty packages which do not have sub-packages. In case that user wants to create new class under that empty package.
