### ISSUE TITLE
JDK 11 dependency tree displays only java.rmi module packages

### ISSUE THREAD

**Issue by argherna** [Microsoft/vscode-java-dependency#130]
Using VS Code 1.30.1, version 0.2.0 of the extension, when I expand the view under the JRE System Library [JavaSE-11] node, I see the modules as expected. However any module I expand only shows the contents of the java.rmi module. I expect to see the packages contained in the module (e.g. java.base should not display any of the java.rmi packages).

**Comment by andxu** [comment]
Dup as https://github.com/Microsoft/vscode-java-dependency/issues/121
