### ISSUE TITLE
command 'java.project.create' not found

### ISSUE THREAD

**Issue by Franguestclain** [Microsoft/vscode-java-dependency#142]
I'm starting with Java and I want to create a full project with this extension, but I don't know why this error comes up, I have already install the JDK and the language support for Java extension and  also my editor it's updated

![image](https://user-images.githubusercontent.com/25850692/51078173-add2d580-166e-11e9-965b-5b61a70fe9b8.png)

**Comment by ayyemichelle** [comment]
How did you resolve this issue?

**Comment by awarmfastbear** [comment]
In case it helps anyone, I resolved this issue by specifying my java.home path in my VS Code settings.json

e.g.

`"java.home": "/path/to/your/javaJDK/jdk1.8/"`
