### ISSUE TITLE
Ability to auto refresh instead of manually clicking

### ISSUE THREAD

**Issue by goxr3plus** [microsoft/vscode-java-dependency#144]
Can we add the ability to auto refresh instead of having to click the refresh button manually all the time ?

![code_2019-02-28_16-27-59](https://user-images.githubusercontent.com/20374208/53573297-d3139880-3b75-11e9-88c0-5e3fad7af2d4.png)

Let's say with Native System Hooks or something ... like Eclipse does ... :)

**Comment by yaohaizh** [comment]
Fixed.

**Comment by goxr3plus** [comment]
Thank you :)
