### ISSUE TITLE
Display non-Java files in Java Projects explorer

### ISSUE THREAD

**Issue by goxr3plus** [microsoft/vscode-java-dependency#145]
Eclipse has a very good structure for Java Projects . 

It shows pom.xml file of project and the other outer project folders . 

![eclipse_2019-02-28_16-35-08](https://user-images.githubusercontent.com/20374208/53573747-d52a2700-3b76-11e9-80ac-801b6d887af9.png)

Here i can't find those  and all the time i am going between explorer and Java Dependencies Viewer : 
![code_2019-02-28_16-31-32](https://user-images.githubusercontent.com/20374208/53573577-6a78eb80-3b76-11e9-881c-937fee59d923.png)

Like let's add also everything that Explorer contains ... like the outer folders and showing pom.xml etc .. look how beautiful is in Eclipse ( one for all , not going back and forth with two viewers like here...)

And finally ... for god mercy why we can't create new file or delete like we can do in Explorer ? Come on .... :) Make me love vs code more by adding those please :)

**Comment by yaohaizh** [comment]
When we start this project, we are mainly focusing provide functionalities the file explorer missed. But we will consider these in future. 
 
And thanks for your supports.

**Comment by goxr3plus** [comment]
It's ao important that without it it's practically useless. I can just use
IntelliJ or Eclipse or Netbeans..


Please we need it :)
