### ISSUE TITLE
The icon of package make me confused

### ISSUE THREAD

**Issue by lxhmavis** [microsoft/vscode-java-dependency#151]
### Configuration:
```
Vscode: 1.32.3
JDK: 1.8.0_202/11.0.1
OS: Win/Mac/Linux
Build: 0.4.0
```
The package is out of the class, why the "{}" is in class. And there are two package icons, it makes me confused. 
![image](https://user-images.githubusercontent.com/41565966/55065061-1cdc9980-50b6-11e9-8615-4b64a0ef3139.png)

**Comment by jdneo** [comment]
Has been fixed in https://github.com/microsoft/vscode-java-dependency/pull/235

Also the icon for `package` has been unified in https://github.com/microsoft/vscode-java-dependency/pull/241
