### ISSUE TITLE
Exposing project classpath information

### ISSUE THREAD

**Issue by ChrisTrenkamp** [microsoft/vscode-java-dependency#158]
Original issue: [https://github.com/redhat-developer/vscode-java/issues/934](https://github.com/redhat-developer/vscode-java/issues/934)

For other plugins (e.g. SonarLint) to support Java, the classpath information needs to be exposed.

Here's an example of what needs to be exposed.  [https://docs.sonarqube.org/display/PLUG/Java+Plugin+and+Bytecode](https://docs.sonarqube.org/display/PLUG/Java+Plugin+and+Bytecode).

**Comment by jdneo** [comment]
Has been supported at the Java Language Server side. See: https://github.com/redhat-developer/vscode-java/pull/1212
