### ISSUE TITLE
After rename a java file, it can not be opened.

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/vscode-java-dependency#163]
### Configuration:
```
Vscode: 1.35.0
JDK: 1.8.0_201/11.0.3
OS: Win/Mac/Linux
Build: 0.5.0 sign bits
```
### Repro steps:

1. Setting the java.Dependency.Auto Refresh to false
2. Rename one java file
3. Click the file in Java dependencies explorer

### Result:
An error report in bottom right corner:
![image](https://user-images.githubusercontent.com/44559777/59182322-0960ab00-8b9c-11e9-8708-aee07e608c25.png)

After refreshing the explorer, it works fine.

**Comment by jdneo** [comment]
This is as expected if auto-refresh is disabled.
