### ISSUE TITLE
Cannot create Java project with RED Hat Extension installed and java openJDK8 installed in WSL

### ISSUE THREAD

**Issue by JacobGeoGeek** [microsoft/vscode-java-dependency#178]
hello everyone,
Show I have java jdk 8 in WSL and i trying to create java project with Red Hat extension. but whenever i click CTRL+SHIT+P and i choose Create Java project, I have this Error:

`EPERM: operation not permitted, copyfile '/home/jacobchaar/.vscode-server/extensions/vscjava.vscode-java-dependency-0.5.1/templates/.project' -> '/mnt/c/Users/jacob/Documents/Programmation/Java/Tuto/HelloWorld/.project'
`
Note that I use Remote WSL

**Comment by jdneo** [comment]
Hi @JacobGeoGeek,

Just as the error message shows, you might need to configure your folder's access permission.

I'm closing this issue since it seems that it's out if the scope. But feel free to comment if you have more questions.
