### ISSUE TITLE
Create Java Project broken

### ISSUE THREAD

**Issue by yaohaizh** [microsoft/vscode-java-dependency#179]
- Install extension
- Try to invoke "Java: Create Project" to create a project.

Expected: 
A prompt to add a new project

Actually: 
Nothing happened

**Comment by testforstephen** [comment]
@Vigilans could you have a look at this issue?

**Comment by Vigilans** [comment]
Sure, I'll have a look.

**Comment by Vigilans** [comment]
This issue cannot be reproduced in Linux, Mac & Windows machine with openjdk 11, so I'll close it for now.

**Comment by akaroml** [comment]
Seems like some users are still experiencing this error. Could you follow up with the user?

redhat-developer/vscode-java#1141

**Comment by Vigilans** [comment]
I see.

This issue and the linked issue's behavior seems not the same, and I'll have a look into the mechanism of how the command gets called.

**Comment by jdneo** [comment]
Close for inactive. If anyone still has the problem, feel free to leave a comment,

Thanks

**Comment by aditya-shrivastavv** [comment]
I think i Solved it, I was Facing this Problem too.
On Clicking create data project nothing happend for 2 sec and then a error poped up saying - 'java.project.create' not found.
Solution - (At least worked for me😅)
YOU HAVE TO ADD JAVA TO PATH.

Here are the steps to do that -
1. Find Java Folder in you C drive and then inside JDK folder, copy the path of bin folder (it will look like this - C:\Program Files\Java\jdk-15.0.1\bin)
2. Search Environment Variables in settings.
3.  A system Properties tab will open.
4. click on environment variables button.
5. Inside System variables Group search for the varible named 'Path'.

**Comment by Asapkim** [comment]
Can you provide some images
