### ISSUE TITLE
Java Dependencies not showing projects

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-dependency#189]
> Originally created by @sandeepamilineni at https://github.com/redhat-developer/vscode-java/issues/1094

[provide a description of the issue]

##### Environment
JAVA_VERSION="1.8.0_201"
OS_VERSION="5.2"
OS_ARCH="amd64"
VSCODE Version: 1.39.1 (user setup)
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:31:28.683Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

##### Steps To Reproduce

1. Install Java extension pack
2.  Import 4 existing maven projects.
3.  

I[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
![image](https://user-images.githubusercontent.com/2767069/66720839-76709f80-ee1f-11e9-92b5-8929d03f686a.png)

only 2 projects are visible in **Java Dependencies** section. 
##### Expected Result
All java projects should be visible in **Java Dependencies** section

**Comment by Vigilans** [comment]
@sandeepamilineni Could you try the following methods to see if it helps?
1. Click the refresh button;
2. Goto %APPDATA%\Code\User\workspaceStorage, remove your workspace folder (If you can't figure out which one, just remove all the folders in it).

If those do not help, could you kindly upload this project to help us reproduce your issue?

**Comment by sandeepamilineni** [comment]
Attached 2 projects. One visible and other not visble in "Java Dependencies" section

[workdir - Copy.zip](https://github.com/microsoft/vscode-java-dependency/files/3774617/workdir.-.Copy.zip)

**Comment by Vigilans** [comment]
@sandeepamilineni Thanks! I'll take a look recently.

**Comment by jdneo** [comment]
To change the JDK version of your project, you can use the setting `java.configuration.runtimes` to map your different JDK locations. And directly update the related entries in your `pom.xml` or `build.gradle`. The Java language server will automatically pick the most match one for your project.
