### ISSUE TITLE
Use VSCode-Icons to replace the current art works

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-java-dependency#197]
Here's the current artwork:
![image](https://user-images.githubusercontent.com/16755094/67266670-54dc7b80-f4e3-11e9-8f08-dca17e957f3b.png)

VS Code now supports octicons, and by adopting them, the test status looks more consistent and appealing in the explorer window.
https://code.visualstudio.com/api/references/icons-in-labels
https://octicons.github.com/

**Comment by akaroml** [comment]
The newest tree view icon:
https://github.com/microsoft/vscode-icons/blob/master/icons/light/list-tree.svg

**Comment by jdneo** [comment]
Addressed in https://github.com/microsoft/vscode-java-dependency/pull/205
