### ISSUE TITLE
Creating invisible project instead of Eclipse project

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-dependency#199]
Benefit we can get from this change:
- Support different kind of JDK automatically
- Much easier to configure the dependencies.

**Comment by stevenzlee** [comment]
Hi, can you please add back the option to create an Eclipse project (aside from the current empty project)? I'm a beginner of Java and have relied on the option to create my learning projects according to lectures that's based on Eclipse... without the option I'll have to install Eclipse instead. Thanks.

**Comment by jdneo** [comment]
@stevenzlee Maybe you can try [this](https://marketplace.visualstudio.com/items?itemName=mellena1.eclipse-new-java-project)?

**Comment by stevenzlee** [comment]
Already tried it when this extension stopped making the Eclipse project, and it produces a `java.lang.Object cannot be resolved. It is indirectly referenced from required.` error from time to time, I tried googling that error but still clueless. 

I managed to install v0.9.0 of this extension in VSCode, and it works out for me. I'll stick to this version for now.

**Comment by jdneo** [comment]
I also tried that extension actually but not able to see that exception. 🤔
