### ISSUE TITLE
How do those `command` work?

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode-java-dependency#200]
Hello,

I found that several commands are executed in the project such as `java.getPackageData`. But I cannot find any ts code about how this command works. 

Is this command imported from other projects? 

If I want to write a vsc extension to extract all dependency jars, is there any developer tool helping me to do this?

**Comment by Vigilans** [comment]
Hi @HaoboGu, Some of the commands are forwarded to java language server (`jdt.ls`) to be executed, including the mentioned `java.getPackageData`:

https://github.com/microsoft/vscode-java-dependency/blob/e22a7212534273784a707299a2e94cb52a7a8462/src/java/jdtls.ts#L13-L15

`Commands.EXECUTE_WORKSPACE_COMMAND` just forwards `Commands.JAVA_GETPACKAGEDATA` to the language server, and gets it handled in `DelegateCommandHandler` implementation:

https://github.com/microsoft/vscode-java-dependency/blob/e22a7212534273784a707299a2e94cb52a7a8462/jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/CommandHandler.java#L23-L37

So `java.getPackageData` is actually working in [`PackageCommand.getChildren`](https://github.com/microsoft/vscode-java-dependency/blob/e22a7212534273784a707299a2e94cb52a7a8462/jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java#L89).

**Comment by HaoboGu** [comment]
@Vigilans Thanks for the reply! 

I checked `PackageCommand.getChildren`, it seems that all dependencies are analyzed and imported by `IJavaProject.findPackageFragmentRoot`. 

If the project is using Maven or Gradle, will the imported packages be analyzed? Can we get all `.jar` resources?

**Comment by jdneo** [comment]
@HaoboGu Do you mean you want to get the project's classpath?

**Comment by HaoboGu** [comment]
> @HaoboGu Do you mean you want to get the project's classpath?

Hi, I want to get all `.jar` files of dependencies of current project which are downloaded by Maven. So the first step is to get information about dependencies. It seems that this work is done by the language server, and I have figured it out another way to get all I need. I will close this issue. Thanks for the reply!

BTW, I have another question now: how does the extension communicate with language server? By command line? Does this mean I have to install the language server to local machine while I install the extension?

**Comment by jdneo** [comment]
Take the Java Dependency Viewer as an example, we will write the Java code and build them into a jar file. This jar will be loaded by the Java Language Server during the start-up. Then, to call the Java code, you can do what @Vigilans has mentioned in https://github.com/microsoft/vscode-java-dependency/issues/200#issuecomment-546178079.

**Comment by HaoboGu** [comment]
This is quite clear, thank you! @jdneo
