### ISSUE TITLE
Classpath entry with path empty not showing correctly in Eclipse project

### ISSUE THREAD

**Issue by Vigilans** [microsoft/vscode-java-dependency#203]
When classpath's path is empty, the packageRootNode would show an empty name here:
![image](https://user-images.githubusercontent.com/20227484/68656078-1b3fe300-056c-11ea-82ca-40f982e1e862.png)
![image](https://user-images.githubusercontent.com/20227484/68656120-2d218600-056c-11ea-8308-1a60a7bbed3e.png)

As a comparison, Eclipse IDE exposed it to outer hierachy:
![image](https://user-images.githubusercontent.com/20227484/68656028-06634f80-056c-11ea-86f2-9a80dab945a8.png)

**Comment by jdneo** [comment]
Should have been fixed in the latest Project Manager for Java

![image](https://user-images.githubusercontent.com/6193897/144177585-05d68219-984e-4b69-b1a5-7ed257872f7e.png)
