### ISSUE TITLE
no right click action on file or folder

### ISSUE THREAD

**Issue by jason919** [microsoft/vscode-java-dependency#207]
the flat package view is nice, however, I lose all the right click functions on files and folders.
Not sure if that's even possible with current VS code

**Comment by testforstephen** [comment]
We don't support right click on the **Java Dependency View** yet. Do you mean you lose the right click on the **File Explorer**?

**Comment by jason919** [comment]
Right click still works on the file explorer. 
If the java dependency view supports all the right click, then it can replace the file explorer

**Comment by maxandersen** [comment]
+1 on this as without it the java dependency view is not really adding much value besides being a nice indicator that Java LSP actually is enabled. For now I'm minimizing the java dependency view as all the contextual actions I seem to use all the time are missing.

**Comment by testforstephen** [comment]
Menus in progress:
- [x] Reveal in Explorer
- [x] Copy Path
- [x] Copy Relative Path
- [ ] Copy Qualified Name (enable for package and class)

If you want more menus to be added to dependency view, please add comment below.

**Comment by maxandersen** [comment]
How about all of them ? :)

Here are the ones I keep going for and then have to go to resource view on:

- [ ] Open to the Side
- [ ] Reveal in Finder
- [ ] Open in Terminal (for directories mainly)
- [ ] all the revision commands
- [ ] cut, copy, rename, delete

**Comment by 0dinD** [comment]
Any updates on this? I noticed [you can now](https://github.com/microsoft/vscode-java-dependency/pull/299) create new classes/packages from the context menu, which is great! But it's really annoying to have to go back to the file explorer when you need to rename or delete said class/package. I agree with the previous comment, but rename and delete on class/package nodes is the feature that I miss the most!

**Comment by jdneo** [comment]
@0dinD Thank you for the suggestion. That's a valid request. I'll take a look these days.

**Comment by benzman81** [comment]
- [ ] New File
- [ ] New Folder

see #598

**Comment by jdneo** [comment]
New File and Folders are implemented in https://github.com/microsoft/vscode-java-dependency/pull/742.

For other actions, there are separate issues to track:
- https://github.com/microsoft/vscode-java-dependency/issues/743
- https://github.com/microsoft/vscode-java-dependency/issues/630

I'm closing this issue. Any new request please file issues separately for each of the actions. Thanks.
