### ISSUE TITLE
Files matching vscode's `file.exclude` setting should be removed from viewer

### ISSUE THREAD

**Issue by Vigilans** [microsoft/vscode-java-dependency#214]
### Current Behavior
![image](https://user-images.githubusercontent.com/20227484/69305567-6db18b80-0c5f-11ea-95f2-b9f094c61f07.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/20227484/69305603-9174d180-0c5f-11ea-98ba-7ebee30b4655.png)

**Comment by aaronsmith1203** [comment]
+1 for this. This adds a lot of bloat to the hierarchical view. The number of `.DS_Store` entries increases the longer your package hierarchy gets.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/54414085/162004670-20a9828a-a07b-4db5-a929-14edaab4d1e2.png">

Many thanks.
