### ISSUE TITLE
The remove button does not work when the include and exclude has the same artifact

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-dependency#222]
![demo](https://user-images.githubusercontent.com/6193897/72310762-8d908900-36bd-11ea-9432-a237c0fe7b91.gif)

**Comment by Vigilans** [comment]
This is not related to the remove button, but related to the glob implementation of java language server:
```java
if (Files.isRegularFile(base)) {
	if (isBinary(base))	{
		binaries.add(base);
	}
	continue; // base is a regular file path
}
```

If the include is a regular file, then the exclude won't come into effect.

This code is written by my mistake, do you think this mistaken behavior (should not exclude when include is an absolute simple path) should be fixed?

**Comment by jdneo** [comment]
@Vigilans We can make some changes at the dependency viewer side to make sure there is no duplicated cases in `include` and `exclude`

Please take a look at https://github.com/microsoft/vscode-java-dependency/pull/223 and let me know if you have any concern.
