### ISSUE TITLE
Cannot select any directory when adding Referenced Libraries, and cannot add it again after deleting

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/vscode-java-dependency#238]
**Configuration:**
Vscode: 1.42.1
JDK:1.8.0_241
OS: Linux
Build: 0.8.0

**Repro steps:**
1.Open Folder
2.Add a jar file or a folder to project classpath
3. Delete the added content
4. Repeat step 2

Result:
1.The user cannot select the desired folder and the directory cannot go forward or backward.
![1be86224-1d21-4e39-9023-f7b55e923b6a](https://user-images.githubusercontent.com/51812626/74521993-4fed7d00-4f55-11ea-8cb2-ceca9ed4e30d.jpg)

2.After deleting the added a jar file or a folder, it cannot be added again
![image](https://user-images.githubusercontent.com/51812626/74522202-bb374f00-4f55-11ea-9af4-f153e971f2c8.png)

**Comment by testforstephen** [comment]
@jdneo could you take a look?

**Comment by jdneo** [comment]
Need some time to investigate this issue. While a workaround is to manually edit the workspace setting: `java.project.referencedLibraries` in `settings.json`
