### ISSUE TITLE
Automatically reveal the open Class in java dependencies

### ISSUE THREAD

**Issue by tomasbjerre** [microsoft/vscode-java-dependency#239]
If I open a Class (see `Step.class` below) I want the Java Dependencies to show me which one of all the `jars` contains that `Class`.

Now I can browse the dependencies and open classes that I find there, but I want to do the opposite.

This would allow me to see other classes in the same package and/or `jar`. I usually end up in a third party `jar` when I browse imported classes in my own code.

![image](https://user-images.githubusercontent.com/439571/74679855-436c5d00-51bf-11ea-8500-6d789aae9488.png)

**Comment by jdneo** [comment]
This is supported. Please make sure you enable the `java.dependency.syncWithFolderExplorer`. (by clicking the 'arrow like' button in the explorer's navigation bar)

Below is an illustration:
![Kapture 2020-03-05 at 10 49 21](https://user-images.githubusercontent.com/6193897/75943166-380f7600-5ecf-11ea-83f3-8f07f5768f29.gif)
