### ISSUE TITLE
ignore missingSerialVersion

### ISSUE THREAD

**Issue by hasanmumin** [microsoft/vscode-java-dependency#250]
Hi, I am trying to ignore missingSerialVersion warning, 
I created .settings/org.eclipse.jdt.core.prefs at project root folder with this settings:
```
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.problem.missingSerialVersion=ignore
org.eclipse.jdt.core.compiler.codegen.inlineJsrBytecode=enabled
org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.8
org.eclipse.jdt.core.compiler.compliance=1.8
org.eclipse.jdt.core.compiler.problem.assertIdentifier=error
org.eclipse.jdt.core.compiler.problem.enumIdentifier=error
org.eclipse.jdt.core.compiler.source=1.8
```
but looks like does not works, can you explain why ?

**Comment by jdneo** [comment]
For the missing serial version Id warning, you can set `org.eclipse.jdt.core.compiler.problem.missingSerialVersion=ignore`

You might want to trigger a full build to update those diagnostics in your project (alt+shift+b, full)

See: https://github.com/eclipse/eclipse.jdt.ls/issues/581

**Comment by jdneo** [comment]
@hasanmumin Is the problem resovled?

**Comment by hasanmumin** [comment]
yes, but I had to copy the same file to all  modules.

**Comment by jdneo** [comment]
If you want to have any feature request about this, feel free to file an issue at: https://github.com/eclipse/eclipse.jdt.ls/issues
