### ISSUE TITLE
Bad semantic highlighting when open myJunit4Test from java dependency

### ISSUE THREAD

**Issue by pl07** [microsoft/vscode-java-dependency#253]
### Environment
 - Vscode: 1.44.1
 - JDK:1.8.0_231
 - OS: Windows, Mac
 - Language support for java: 0.60.0
 - Java dependency: 0.9.0

### Repro steps
1. Open invisible project (make current page only `MyTestNGTest`)
2. Remove all referenced libraries in dependency and reload window
3. Add all referenced libraries in test-libs, open `myJunit4Test` from dependency viewer

### Result
![image](https://user-images.githubusercontent.com/46642771/79429574-4090bb80-7ffa-11ea-8c77-7e022cd0e822.png)

**Comment by Eskibear** [comment]
I'll invesitigate it to find whether it's a vscode issue, or bug of semantic highlighting implmentation.

**Comment by fbricon** [comment]
I'm disabling semantic highlighting by default, it's too annoying: https://github.com/redhat-developer/vscode-java/issues/1396
