### ISSUE TITLE
Trying to find a way to create custom java projects

### ISSUE THREAD

**Issue by tux2603** [microsoft/vscode-java-dependency#254]
Our university is currently transferring our introductory java classes over to vs code, but we need a way to create java projects from a custom template. We already have an extension that's capable of generating the file structure necessary for the project, but as of yet there is no managing of dependencies. I have poked through your source code a bit, but the documentation is a bit slim. Would you be able to supply us with a reference to what functions will have to be called in order to create a new project in the dependency manager? Thank you.

**Comment by jdneo** [comment]
@tux2603 We are just recently working on the [creating project experience](https://github.com/microsoft/vscode-java-dependency/pull/252).

Please let me know if you need more information.

Thanks

**Comment by tux2603** [comment]
Do you know when the new features will be released? We were hoping to start using vs code for the upcoming fall semester.

**Comment by tux2603** [comment]
@jdneo The custom extension is working with the dependencies now, but the .class files are currently going to a hidden directory in the user's home directory. Is there any way to specify a directory in the workspace that the compiled java classes should go. Ideally, this would be a directory called bin/

**Comment by jdneo** [comment]
> Do you know when the new features will be released?

We will run the QA process recently, if everything works fine, then I'll release it. I guess the ETA could be the end of next week.

> Is there any way to specify a directory in the workspace that the compiled java classes should go

Emm, so far it's not supported. Could you explain more to help us understand this request?

**Comment by tux2603** [comment]
Essentially, when eclipse or netbeans create a project, you have a src directory for java source code and a bin directory for the compiled binaries. It wouldn't strictly be necessary for the compiled binaries to go to a customizable directory, but it would be a nice feature to have. 

Essentially, it would be equivalent to setting an output directory on the java compiler, just stored somewhere in the project configuration file.

**Comment by jdneo** [comment]
I see. I suggest to create a feature request for customizing the binary output folder of the standalone project in the [Java Language Server repo](https://github.com/eclipse/eclipse.jdt.ls/issues)

**Comment by tux2603** [comment]
I will look into that. Thanks!

**Comment by jdneo** [comment]
@tux2603 Just FYI the new version might be postponed to next week. If you need the the private build, you can try to build it by your own. Here is the steps:

1. clone the repo
2. cd to the project base path
3. npm install
3. npm run build-server
4. npx vsce@latest package
5. You'll get a .vsix file which can be installed manually.

**Comment by jdneo** [comment]
Use #281 to track the feature request about specifying the output folder
