### ISSUE TITLE
No dependancies shown in JAVA DEPENDANCIES EXPLORER ( using ssh remote)

### ISSUE THREAD

**Issue by jledru** [microsoft/vscode-java-dependency#265]
Hello,

I'm developing on Windows VS code with remote ssh on ubuntu machine

Remote Environment
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven-3.6.3
Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-1009-gcp", arch: "amd64", family: "unix"

Local:
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Issue : 
When I first install the workspace, all went well I could see all java dependancies in the project.
I didn't change anything but now Java Dependancies is desperatly empty. I looked in other threads and the server log file doesn't show specific stuffs : 
![image](https://user-images.githubusercontent.com/60506275/82038289-9dd46700-96a3-11ea-81eb-f40a0d5f25e2.png)
Thanks,

**Comment by jdneo** [comment]
Cannot repro on my side. Could you provide more screenshots
<img width="449" alt="Screen Shot 2020-05-16 at 1 23 37 PM" src="https://user-images.githubusercontent.com/6193897/82111515-861ae280-9778-11ea-8f23-3d397e6028af.png">
 and information about it?

**Comment by jledru** [comment]
Hello,

A capture here:
![image](https://user-images.githubusercontent.com/60506275/82114728-cf5e3880-975e-11ea-94cf-bc58965e40a6.png)
In the worskpace there are several maven projects as you could see. But it seems that there is an issue too as when I click on maven projects it doesn't open pom.xml as I think it should do. Maybe an issue with Maven ... What else would you know ?

**Comment by jdneo** [comment]
@jledru So I guess the problem has been solved now?

**Comment by jdneo** [comment]
Closed since the issue resolved.
