### ISSUE TITLE
Connection time out when create maven project in linux

### ISSUE THREAD

**Issue by pl07** [microsoft/vscode-java-dependency#267]
#### Configuration:
 - Vscode: 1.45.1
 - JDK:11.0.5
 - OS: linux
 - Build: 0.10.2

#### Repro steps:
1. F1 -> Create Java Project -> Maven
#### Result:
![image](https://user-images.githubusercontent.com/46642771/82800807-e1528080-9eae-11ea-9589-9bf255c18cb1.png)

**Comment by jdneo** [comment]
It should be network issue, which is out of scope.
