### ISSUE TITLE
Show both create maven/java project command in palette

### ISSUE THREAD

**Issue by pl07** [microsoft/vscode-java-dependency#268]
#### Configuration:
 - Vscode: 1.45.1
 - JDK:11.0.5
 - OS: windows, mac, linux
 - Build: 0.10.2

#### Result:
![image](https://user-images.githubusercontent.com/46642771/82800970-2080d180-9eaf-11ea-8734-210f1aae76bb.png)

**Comment by jdneo** [comment]
@akaroml @Eskibear IMO, if the centralized `Create Java Project` command is registered into the command palette, the `Create Maven Project` command should be hidden. What do you think?

**Comment by akaroml** [comment]
I would put more weight on showing less entries especially in the case that one points to the other.  But just curious how that is possible since the command registration is static.

**Comment by jdneo** [comment]
It supports when clause when registering command in the palette.

See: https://github.com/microsoft/vscode-maven/pull/488/files

**Comment by akaroml** [comment]
> It supports when clause when registering command in the palette.
> 
> See: https://github.com/microsoft/vscode-maven/pull/488/files

Just curious. Is "when command X is not registered" clause possible?

**Comment by jdneo** [comment]
No, it's not. So far we can only determine it by checking if the related extension is installed or not.

**Comment by jdneo** [comment]
Fixed in https://github.com/microsoft/vscode-maven/pull/488
