### ISSUE TITLE
Locate binary directory in project folder.

### ISSUE THREAD

**Issue by deffence1776** [microsoft/vscode-java-dependency#281]
I am trying to use visual studio code for java to train beginners.

In java project, a binary directory is usually located in project folder.
It is useful for beginners to see binary folder to realize what is "compile".

So, can you change the "no build tool" template, or make it configurable?

I tried to  change ".classpath" file and it worked.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="src" path="_/src"/>
	<classpathentry kind="output" path="_/bin"/>
</classpath>
```

**Comment by jdneo** [comment]
A PR is raised at upstream side: https://github.com/eclipse/eclipse.jdt.ls/pull/1594

Please feel free to comment there is you have any questions.

Thanks

**Comment by jdneo** [comment]
I'll close this issue since the upstream PR has been merged.

Please not that: **The setting will only take effect when it's configured in the WORKSPACE scope**!!
