### ISSUE TITLE
Binaries in referenced libraries cannot update if the binary name is not changed

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-java-dependency#287]
I added a new class to a jar file.

Eventually JD saw it:
<img width="854" alt="Screen Shot 2020-08-02 at 22 55 01" src="https://user-images.githubusercontent.com/738650/89132600-ae171800-d515-11ea-8cc6-7f8ce2255472.png">

But I was unable to import, as you can see on the right of the image.

When I did an import I had no errors:
<img width="442" alt="Screen Shot 2020-08-02 at 22 56 51" src="https://user-images.githubusercontent.com/738650/89132627-ddc62000-d515-11ea-8fcc-9a3936410e07.png">

But no defenition was found either:
<img width="444" alt="Screen Shot 2020-08-02 at 22 57 05" src="https://user-images.githubusercontent.com/738650/89132646-f6363a80-d515-11ea-812d-cbebdfca19d7.png">

I also had a problem where I forgot to make a field public in the jar file, it's a real pain to make vscode pickup the change that I made it public. It would be nice if it could recognize that the hash of a jar is changed and does some effort in picking up the changes. I often feel like I'm the extension of vscode...

**Comment by clankill3r** [comment]
I had to use the same jar in another project, where I had the same problem, so now I could write down the steps I took more easy.

First off, it did show up in the DP viewer. Also the import gave no errors, but when using `Go to Definition`, no definition was found.

- restarting vscode does not help
- synchronizing dependency viewer with folder explorer does not help
- desynchronizing dependency viewer with folder explorer does not help
- `java: refresh` does not help
- `java: clean the language server workspace` does not help

The only thing that works for me is deleting the workspace storage.

OSX 10.12.6
VSCode Version: 1.47.3
extension 0.10.12
all other java extensions are latest as well, except maven, but it's not a maven project.

**Comment by clankill3r** [comment]
Ok, the quickest workaround is to go to `settings.json`, copy and delete the line containing the jar file, then save the file. Wait a few seconds till the Problems show up. Then paste the line back in, save `settings.json`, and voila problem gone.

**Comment by jdneo** [comment]
Hi @clankill3r

By saying `deleting the workspace storage`, what's the actual operation you did?

**Comment by clankill3r** [comment]
I wen't to `/Users/doekewartena/Library/Application Support/Code/User/workspaceStorage` and deleted the right folder there.

**Comment by jdneo** [comment]
It's a bug at the language server side. We need to refresh the classpath even if all the file paths are the same.

@clankill3r Thank you for reporting the issue

**Comment by jdneo** [comment]
The upstream bug has been fixed and should be available in the next `Java Language Support` extension release.

Please note that, if the referenced jar file is in the workspace, VS Code can automatically detect its change, otherwise, you need to **manually click** the refresh button to force the language server refresh the classpath.
![image](https://user-images.githubusercontent.com/6193897/97257631-79cfa100-1851-11eb-9f71-c2bd8e669b74.png)
