### ISSUE TITLE
Descriptive text in settings is not renamed

### ISSUE THREAD

**Issue by pl07** [microsoft/vscode-java-dependency#288]
### Configuration:
Vscode: 1.47.3
JDK: 11.0.7
OS: Win, Mac
Build: https://dev.azure.com/mseng/VSJava/_build/results?buildId=12733441&view=artifacts&type=publishedArtifacts

### Result:
![image](https://user-images.githubusercontent.com/46642771/89164173-52966a00-d5a9-11ea-9cae-c7227d3d6090.png)

**Comment by jdneo** [comment]
fixed in #289
