### ISSUE TITLE
I have Java-SE 1.8. Is it  above SDK 11?

### ISSUE THREAD

**Issue by zhengger** [microsoft/vscode-java-dependency#292]

**Comment by jdneo** [comment]
Please provide more detail about your problem.

**Comment by zhengger** [comment]
> Please provide more detail about your problem.

My problem is about the requirement which requires JDK (version 11 or later). Mine is Java-SE 1.8. I'm not sure if it is okay for this requirement.
Thanks.

**Comment by jdneo** [comment]
Java Language Server need JDK 11 to launch it. So I think you need to upgrade your jdk version. But you can still use javase-1.8 as the language level for your project.

https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-663382692

**Comment by zhengger** [comment]
> Java Language Server need JDK 11 to launch it. So I think you need to upgrade your jdk version. But you can still use javase-1.8 as the language level for your project.
> 
> [redhat-developer/vscode-java#1543 (comment)](https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-663382692)

Thanks.
So JDK 11 is necessary for this extension.  In [your Java Dependency Viewer page](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency), it says the requirement is JDK (version 1.8.0 or later). I think it needs update.

BTW, is OpenJDK 11 ok or not? Mine is mac OS. And how can I set the vscode environment for OpenJDK if ok?
Thanks.

**Comment by jdneo** [comment]
> So JDK 11 is necessary for this extension. In your Java Dependency Viewer page, it says the requirement is JDK (version 1.8.0 or later). I think it needs update.

It's a out-of-date page. We've update the requirement in the [repo's readme](https://github.com/microsoft/vscode-java-dependency#requirements) and things will update after the next release.

> is OpenJDK 11 ok or not?

You can choose whatever JDK distribution you want to use, as long as it's >= 11.

> how can I set the vscode environment for OpenJDK

See https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-663382692

**Comment by zhengger** [comment]
Thanks.
