### ISSUE TITLE
Cannot auto refresh after edit package

### ISSUE THREAD

**Issue by pl07** [microsoft/vscode-java-dependency#305]
### Configuration:
 - Vscode: 1.48.0
 - JDK: 11.0.7
 - OS: Win
 - Build: Id=12872218
### Repro steps:
1. Open a simple/gradle/invisible project
2. Right click to new package or rename or delete package
### Result:
The package change cannot auto refresh, it will only refresh after click refresh button manually.

**Comment by jdneo** [comment]
It turns out that this issue happens when the project has default package. Since the default package and the package root has the same uri, so a conflict happens inside the trie cache.
