### ISSUE TITLE
Images cannot be opened from java projects explorer

### ISSUE THREAD

**Issue by pl07** [microsoft/vscode-java-dependency#309]
### Configuration:
Vscode: 1.48.0
JDK: 11.0.7
OS: Win
Plugin version: 0.11.0
### Repro steps:
1. Open a spring-petclinic project
2. Click files under images
![image](https://user-images.githubusercontent.com/46642771/90712611-0308ab80-e2d6-11ea-8cdd-20445f6fd319.png)

### Result:
Images (.png files) cannot be opened or synchronize with folder explorer.

**Comment by jdneo** [comment]
Seems that the API we used now cannot open binary files.
