### ISSUE TITLE
Can‘t show the java file correctly in invisible project with no src folder

### ISSUE THREAD

**Issue by pl07** [microsoft/vscode-java-dependency#320]
### Configuration:
Vscode: 1.48.2
JDK: 11.0.7
OS: Win/Mac
Plugin version: 0.13.0

### Repro steps:
1. Open a invisible project with no src folder
### Result:
The project manager explorer cannot show the java file correctly.
![image](https://user-images.githubusercontent.com/46642771/91948980-93ada580-ed32-11ea-918e-86db5fe04c1c.png)

![image](https://user-images.githubusercontent.com/46642771/91949127-9e683a80-ed32-11ea-825e-0c9fdce48c39.png)

**Comment by jdneo** [comment]
Fixed by #319
