### ISSUE TITLE
Listing folders first in the "resources" tree hierarchy

### ISSUE THREAD

**Issue by electrotype** [microsoft/vscode-java-dependency#344]
Is there a way to list the folders _first_ in a folder under the `resources` tree? Currently, files and folders are mixed, they are listed alphanumerically.

Instead of:

```
src/main/resources
    |__ folderA
           |__ a.html
           |__ b.html
           |__ subfolderB
                 |__ c.html
```
I'd like to see:

```
src/main/resources
    |__ folderA
           |__ subfolderB
                 |__ c.html
           |__ a.html
           |__ b.html
```

Folders are listed first everywhere in my VSCode editor, except in that "resources" tree of the "Java projects" section. Am I missing some obvious configuration?

**Comment by jdneo** [comment]
@electrotype Thank you for the feedback. It's not supported yet.
