### ISSUE TITLE
The export Jar process is beginning without selecting path to generate.

### ISSUE THREAD

**Issue by chenyuanmac** [microsoft/vscode-java-dependency#351]
**Configuration:**

Vscode: 1.50.1
JDK: 11.0.3
OS: Win
Plugin version: 0.14.0

**Repro steps:**

1.Change  the setting: Java->Project->Export Jar: Target Path to "AskUser";
2.Click export Jar button in the title of JAVA PROJECTS;
3.Select "without main class" and select the elements;
4.Click "ok".

**Result:**
The export Jar process is beginning without selecting path to generate and click "generate" button ,it dose not respond.
![image](https://user-images.githubusercontent.com/70991161/96106982-6bf35500-0f0e-11eb-88b2-11aa741cf2de.png)

**Comment by chenyuanmac** [comment]
In build:13354307 resloved the issue"The export Jar process is beginning without selecting path to generate.",but when I click  the "generate" button ,it still dose not respond, and click "cancel" button ,there is an error window is VSCode.

![image](https://user-images.githubusercontent.com/70991161/96244219-5a767f80-0fd8-11eb-801d-a8910bfe6abd.png)

**Comment by CsCherrYY** [comment]
> In build:13354307 resloved the issue"The export Jar process is beginning without selecting path to generate.",but when I click the "generate" button ,it still dose not respond, and click "cancel" button ,there is an error window is VSCode.
> 
> ![image](https://user-images.githubusercontent.com/70991161/96244219-5a767f80-0fd8-11eb-801d-a8910bfe6abd.png)

@chenyuanmac 
Thanks, I think you may input the file name before you click the `generate` button, or it will not respond. Anyway, the undefined notification is still a bug, I will fix it later.
