### ISSUE TITLE
"Java: Create java project" command is not working

### ISSUE THREAD

**Issue by mdabdulnazar** [microsoft/vscode-java-dependency#354]
When I try to execute it, nothing happens.

Mac OS **10.14.6**
VSCode **1.50.1**
Project Manager for Java **0.13.0**
Language Support for Java(TM) by Red Hat **0.69.0**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

**Comment by jdneo** [comment]
The current version for this command requires the Java Language Server to fully activated before executing.

We have changed the behavior to remove this requirement and the change will be released very soon.

I'll update in this thread if the new version is released. Please stay in tune.

**Comment by jdneo** [comment]
0.14.0 is just released

**Comment by mdabdulnazar** [comment]
In my case, the language server was not fully activated (running endlessly). So that caused the problem as you have said. After updating to 0.14.0, the issue is solved.

Thanks.
