### ISSUE TITLE
Add a when clause to the contributed explorer view such that it is only activated when the workspace has a java project open

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode-java-dependency#372]
The extension contributes its view when I am not in a Java project. I am currently working in a Python project without any Java files. Could you please add a when clause as mentioned in the referenced comment to only show the view contributions when in a Java project?

Context: https://github.com/microsoft/vscode-java-test/issues/793, https://github.com/microsoft/vscode-java-test/issues/793#issuecomment-723045656

https://github.com/microsoft/vscode-java-dependency/blob/master/package.json#L450

**Comment by tristan957** [comment]
Would it also be possible to add a name, contextualTitle, and icon? these would greatly benefit people who move the view into the Activity Bar like myself.

https://code.visualstudio.com/api/references/contribution-points#contributes.views

**Comment by jdneo** [comment]
> Would it also be possible to add a name, contextualTitle, and icon?

I created a new issue to track this: #396

**Comment by tristan957** [comment]
@jdneo I am still seeing the project explorer in the Activity Bar even when I have no workspace/folder/file open.

![image](https://user-images.githubusercontent.com/11936772/102309015-78efed00-3f2d-11eb-8096-c60193000f07.png)

Is this intended?

**Comment by jdneo** [comment]
Do you mean the button `Create Java Project`. If that is the case, yes it's intended.

Actually the Java Project explorer is not shown according to your screenshot, we just register a welcome view into the file explorer to provide a shortcut to create a new Java project.

**Comment by tristan957** [comment]
Oh really interesting. Thanks for clarification.
