### ISSUE TITLE
java.project.referencedLibraries not available at project level (settings.json)

### ISSUE THREAD

**Issue by gpaglia** [microsoft/vscode-java-dependency#373]
We have written the needed data into your clipboard 
Issue Type: <b>Bug</b>

The "java.project.referencedLibraries" works only at workspace level, not at project level.
Contrary to what is described in the online docs (https://code.visualstudio.com/docs/java/java-project), configuring the "referencedLibraries" within the project's settings.json does not work, and the configuration item is actually greyed out.
Moreover, no "java.project.referencedLibraries" setting is present within the settins of the Project Management for Java extension.
This is also contrary to common sense as tipically the libraries a project depends on and their locations are specific to each project, so I wonder what's the sense of having it configured only as a workspace setting.

Extension version: 0.14.0
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux arm 4.19.115-v7+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (22.29GB free)|
|Process Argv|--crash-reporter-id 3098aa30-2015-4204-96f0-23a8d715918e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: pi3-1|
|OS|Linux arm 4.19.115-v7+|
|CPUs|ARMv7 Processor rev 4 (v7l) (4 x 600)|
|Memory (System)|0.90GB (0.13GB free)|
|VM|0%|
</details>
because it was too large to send. Please paste.

**Comment by jdneo** [comment]
The setting `java.project.referencedLibraries` is not provided by this extension. It's a setting from [Language Support for Java(TM) by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java).

This extension is only used to expose this setting with a UI entry.

By saying `not at project level`, do you mean you want to set it in the workspace folder level?

**Comment by gpaglia** [comment]
Yes, exactly. I have multiple project folders in the workspace and each has
a different set of libraries and library locations.

Gianni

Il lun 9 nov 2020, 01:55 Sheng Chen <notifications@github.com> ha scritto:

**Comment by jdneo** [comment]
Thanks. This is an issue related with Java Language Server: https://github.com/eclipse/eclipse.jdt.ls/issues/1303. Once the upstream supports the folder scope, then we can set it to folder level.

As a workaround, you can open multiple VS Code instance for different folders.
