### ISSUE TITLE
Add a name, contextual title and icon for the Java Project Explorer

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-dependency#396]
Would it also be possible to add a name, contextualTitle, and icon? these would greatly benefit people who move the view into the Activity Bar like myself.

https://code.visualstudio.com/api/references/contribution-points#contributes.views

_Originally posted by @tristan957 in https://github.com/microsoft/vscode-java-dependency/issues/372#issuecomment-723159772_

**Comment by tristan957** [comment]
Perfect thanks @jdneo

**Comment by tristan957** [comment]
@jdneo in my effort to open similar issues across various extensions regarding this issue, I have become quite comfortable with this aspect of the VSCode API and would be more than happy to add a PR for this assuming there is some icon you would like me to use :). Not sure if one already exists within the context of the project.

**Comment by jdneo** [comment]
I'll ask the team if we need a new contextual icon and let you know

**Comment by tristan957** [comment]
The new icon looks really good. Thanks. I think that came in the new update 🤔 .

**Comment by jdneo** [comment]
This task is not started yet. Did you mistake the icon of File Explorer to the contextual icon?

**Comment by tristan957** [comment]
Hmm I saw the Maven logo in the Activity Bar and mistakenly assume that was the icon.
