### ISSUE TITLE
The project name in Java projects explorer is not change when user change maven artifactId

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-java-dependency#410]
### Environment:

- OS: Win 10/Mac/Linux
- Vscode: 1.51.1
- Vscode java project manager: 0.15.0

### Actual:
![image](https://user-images.githubusercontent.com/41051257/101753407-8bbd8880-3b0d-11eb-98ac-307a8192dba3.png)

**Comment by ZhengJun003** [comment]
this is in falt view, this is by design

**Comment by jdneo** [comment]
This is because the change will not be consumed by the Java Language Server.

One way to update it is trigger the command `Java: Clean Java Language Server Workspace`  and restart to invalidate the cache.
