### ISSUE TITLE
Can't add custom folder into source path

### ISSUE THREAD

**Issue by weiker** [microsoft/vscode-java-dependency#411]
I hava some java file generated by maven thrfit plugin in target/generated-sources/thrift , these file haven't been add into java source path ,but strangly target/generated-sources/protobuf/java created by maven protobuf plugin was added .
I tried manualy add the path target/generated-sources/thrift by click the option "Add Folder to Java Source Path" in right-click menu ,it shows :
![image](https://user-images.githubusercontent.com/16322689/101757108-b6114500-3b11-11eb-8096-6725e506e7b6.png)
 So I tried use build-helper-maven-plugin config like this:
`            <plugin>`
`                <groupId>org.codehaus.mojo</groupId>`
`                <artifactId>build-helper-maven-plugin</artifactId>`
`                <version>1.8</version>`
`                <executions>`
`                    <execution>`
`                        <id>add-source</id>`
`                        <phase>generate-sources</phase>`
`                        <goals>`
`                        <goal>add-source</goal>`
`                        </goals>`
`                        <configuration>`
`                       <sources>`
`                            <source>src/java/main</source>`
`                            <source>src/java/generated-sources</source>`
`                        </sources>`
`                        </configuration>`
`                    </execution>`
`                </executions>`
`            </plugin> `
 but  it's still not work . 
How can I add generated-sources folder into Java source path?

**Comment by jdneo** [comment]
Please see: https://github.com/redhat-developer/vscode-java/issues/177#issuecomment-673333479
