### ISSUE TITLE
Add multiple folders to src path

### ISSUE THREAD

**Issue by yababer** [microsoft/vscode-java-dependency#412]
We are trying to make this work with a Bazel mono-repo and are wondering if there is a programmatic way to add multiple src folders to the .classpath file?

Right now it seems to add the first src/main/java folder if finds to the .classpath file and then stops.  If you right-click on another folder and add it to the java source path that works fine.

For example:

```
<classpath>
        <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
        <classpathentry kind="src" path="{default added folder 1}"/> 
        <classpathentry kind="src" path="{manually added folder 2}"/>
<classpath>
```

It would be nice to have a config like this:

```
  "java.project.srcs": [
    "/src/main/java",
    "/src/test/java"
  ]
```

For example, this shell script exports the desired src folders.

`SRC_PATHS=$(find . -type d -path '*/src/main/java' -o -path '*/src/test/java')`

Hopefully, there is another, simpler way to do this.

**Comment by jdneo** [comment]
Currently the Java Language Server does not support Bazel. By doing `right-click on another folder and add it to the java source path`. It's actually treat the project as a no build tool project.

I'm actually curious if that really works for your Bazel project?

**Comment by yababer** [comment]
It is a hack for sure but it does seems to work.  Agreed we are setting this up as a no build tool project.

We basically use the dependency glob setting to find the maven jars in the external directory under bazel-{source}.  That works well.

The annoying part is you have to right click on each src folder to add it to the Java path source.

So if I had two projects, I would need to add 4 folders:

./project1/src/main/java
./project1/src/teat/java
./project2/src/main/java
./project2/src/teat/java

One would already be there, so 3 folders to right click on and add.

We verified this in the auto generated .classpath file each src path was added.

Once you add in all src paths, things work in the IDE.

It is not as seemless as using maven, for sure.

-- Yezdaan

On Dec 10, 2020, at 9:14 PM, Sheng Chen <notifications@github.com> wrote:

﻿

Currently the Java Language Server does not support Bazel. By doing right-click on another folder and add it to the java source path. It's actually treat the project as a no build tool project.

I'm actually curious if that really works for your Bazel project?

**Comment by jdneo** [comment]
The team is now thinking about the classpath management experience(source path, jdk, dependencies) as a whole big feature.

The rough idea is users can manage the classpath in a webview. I'll update if we have anything new.

**Comment by jdneo** [comment]
The upstream issue has been fixed.

In the next version, you should be able to use the setting `java.project.sourcePaths` to specify your source paths for the project **without any build tools**

**Comment by siddh78** [comment]
Can we define the output folder correspnding to each source path ?
