### ISSUE TITLE
NPE error when open non-project file

### ISSUE THREAD

**Issue by xqzlgy2** [microsoft/vscode-java-dependency#418]
When we open a non-java file which doesn't belong to the opened project (e.g. execute `Java: Open Java Language Server Log`), LS will throw NPE error like below:

![image](https://user-images.githubusercontent.com/30518415/102054458-6c33a200-3e24-11eb-888c-75e076fa8a1b.png)
![image](https://user-images.githubusercontent.com/30518415/102054473-748bdd00-3e24-11eb-8482-8bb87dd11439.png)

**Comment by testforstephen** [comment]
Yes, i also saw this NPE many times.
