### ISSUE TITLE
When I save the file, "EXPLORER" will automatically expand and display

### ISSUE THREAD

**Issue by yaowenzhou** [microsoft/vscode-java-dependency#430]
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
vscode-java-dependency version: v0.16.0

description:
When I set the configuration item "java.dependency.showMembers" to true, saving the java file will cause the "EXPLORER" in the sidebar to be opened, just as if I actively clicked it with the mouse.
The following is a gif, please note that when the configuration item is true and false, when I save the java file, the left sidebar changes.

![java dependency showMembers bug](https://user-images.githubusercontent.com/60352284/103254914-4aa8ed80-49c2-11eb-9b9d-9db7318e02e6.gif)

**Comment by jdneo** [comment]
Thanks for reporting this.

Just FYI, It's recommended to use the `OUTLINE` view to see the members of a class, you can use that view before this is fixed.
