### ISSUE TITLE
More default settings for 'Export Jar' - skip 'Determine Elements'

### ISSUE THREAD

**Issue by timmclaurin** [microsoft/vscode-java-dependency#431]
First of all can I just say how much I love this extension. Thanks for all the hard work!

At the moment, when you export Jar file, the default is to have all referenced libraries selected to export along with bin. This is not always ideal when we are building a small plugin and the referenced libraries are just there for ... ... reference. :) The Jar file with just my code is ~14kB, all referenced libs is > 15MB.

Can we have a setting where we define the default includes in the Jar export and bypass the "Determine Elements" selection all together? This would greatly speed up the failure rate of my code... 

This is the "offending" screen.
![image](https://user-images.githubusercontent.com/11536209/103449658-5d991780-4c79-11eb-82f9-0f2b0403835f.png)

Thanks,

Tim

**Comment by jdneo** [comment]
@CsCherrYY Could you please take a look?

**Comment by CsCherrYY** [comment]
@timmclaurin Thanks a lot for your enthusiasm and suggestion on the extension!

Currently, we offer an option to custom the export jar process for you. Here is a [wiki page](https://github.com/microsoft/vscode-java-dependency/wiki/Export-Your-Project-to-a-Jar#advanced-custom-export-task) talking about the usage of export task.

In your case if you just want to skip the `Determine elements` wizard with all the referenced libraries unselected, you can follow the [wiki page](https://github.com/microsoft/vscode-java-dependency/wiki/Export-Your-Project-to-a-Jar#advanced-custom-export-task), keep only `${compileOutput}` in the `elements` list of the task definition. After that, you can run the custom task to export jar and the `Determine elements` wizard will be skipped.

**Comment by timmclaurin** [comment]
Awesome! Thank you.

This is great. I made my task the default so I can execute it with Ctrl+Shift+B.

In case some one else needs this, this is what I have in my tasks folder:

{

    "version": "2.0.0",
    "tasks": [
        {
            "type": "java",
            "label": "java: Quick Jar Export",
            "targetPath": "${workspaceFolder}/${workspaceFolderBasename}.jar",
            "elements": [
                "${compileOutput}"
            ],
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
  }
