### ISSUE TITLE
Maven project has display problems in some projects

### ISSUE THREAD

**Issue by 1073809739** [microsoft/vscode-java-dependency#432]
{
  message: '[Error - ]  Problem load project library \n' +
    'ttt does not exist\n' +
    'Java Model Exception: Java Model Status [ttt does not exist]\r\n' +
    '\tat org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:573)\r\n' +
    '\tat org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2525)\r\n' +
    '\tat org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2382)\r\n' +
    '\tat org.eclipse.jdt.internal.core.JavaProject.getRawClasspath(JavaProject.java:2411)\r\n' +
    '\tat com.microsoft.jdtls.ext.core.PackageCommand.getContainers(PackageCommand.java:255)\r\n' +
    '\tat com.microsoft.jdtls.ext.core.PackageCommand.getChildren(PackageCommand.java:104)\r\n' +
    '\tat com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:31)\r\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)\r\n' +
    '\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)\r\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)\r\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)\r\n' +
    '\tat org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)\r\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)\r\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)\r\n' +
    '\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)\r\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)\r\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)\r\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)\r\n' +
    '\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)\r\n',
  level: 'info',
  timestamp: '2021-01-04 00:08:55.358'
}

**Comment by jdneo** [comment]
@1073809739 Could you provide detailed steps for reproduce? And it will be helpful if a sample project can be provided.
