### ISSUE TITLE
Command 'Java: Export Jar...' resulted in an error (command 'java.view.package.exportJar' not found)

### ISSUE THREAD

**Issue by LlamasAreAwesome** [microsoft/vscode-java-dependency#436]
Hi everybody,

**Describe the bug**
I got a problem when I wanted to create a jar file. I can successfully compile and run the project but it is not possible to export a jar file.
I was working on a project the whole day and I already did some jar exports. But suddenly it was not working anymore. Even when I create a new project, older projects, or no maven projects... Even on my other machine is was not working anymore. 

**I already tried**
Uninstalled VsCode and deleted all files in AppData/Local/Program/ and .vscode. Uninstalled all Java JDKs etc. 
Reinstalled Java 11 and VsCode with the Java Extension Pack. Still the same problem!
As well I found [this](https://stackoverflow.com/questions/49534068/command-not-found-in-vscode-extension) and checked if the 'java.view.package.exportJar' is missing in the package.json file, but it was already there.

I'll be very happy if some has a solution or can provide me with some good ideas to fix it.

**Environment:**
 - OS: Win 10 x64
 - Java 11 installed
 - VsCode with Java Extension Pack installed

**Comment by jdneo** [comment]
@LlamasAreAwesome Basically, this means that the Java Language Server is not activated successfully.

Is there any output information you can provide to us? See: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting. And let me know if you need more help.

**Comment by LlamasAreAwesome** [comment]
Thank you for your help!
I reactivated the Java Language Server and it seams to me that it is running perfectly fine.
But I got this errors from the `Developer: Toogle Developer Tools`.
```
ERR Cannot read property 'rows' of undefined: TypeError: Cannot read property 'rows' of undefined
	at u.open (c:\Users\LlamasAreAwesome\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:15:67012)
	at y.startSendingEvents (c:\Users\LlamasAreAwesome\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:842:366)
	at y.$startExtensionTerminal (c:\Users\LlamasAreAwesome\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:846:607)
```

``` 
workbench.desktop.main.js:4574 TypeError: Cannot read property 'slice' of undefined
	at u.printTask (c:\Users\LlamasAreAwesome\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:15:66825)
	at c:\Users\LlamasAreAwesome\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:15:66705
	at Array.forEach (<anonymous>)
	at u.printTasks (c:\Users\LlamasAreAwesome\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:15:66689)
	at c:\Users\LlamasAreAwesome\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:15:66638
	at l.fire (c:\Users\LlamasAreAwesome\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:801)
	at Object.e.updateServerTask (c:\Users\LlamasAreAwesome\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:248374)
	at c:\Users\LlamasAreAwesome\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:15:44701
	at c:\Users\LlamasAreAwesome\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:75349
	at c:\Users\LlamasAreAwesome\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:75563
	at Immediate._onImmediate (c:\Users\LlamasAreAwesome\.vscode\extensions\redhat.java-0.73.0\dist\extension.js:1:77117)
	at processImmediate (internal/timers.js:439:21)
```

In the log file from `Java: Open Java Language Server log file` there aren't any errors. It is 200 lines long so I don't want to attach it here. You can have a look here: [https://1drv.ms/u/s!AiM5T7BzhWEvgekCYZ-BNsx7Ag86gQ?e=k2Vsgb](https://1drv.ms/u/s!AiM5T7BzhWEvgekCYZ-BNsx7Ag86gQ?e=k2Vsgb)

**Comment by jdneo** [comment]
Would you mind to share some screenshots or gifs?

**Comment by LlamasAreAwesome** [comment]
Yeah, sure!
Here they are: [https://1drv.ms/u/s!AiM5T7BzhWEvgekFwYBK1BmMJQHrdg?e=owQ7jg](https://1drv.ms/u/s!AiM5T7BzhWEvgekFwYBK1BmMJQHrdg?e=owQ7jg)

I got as well some new findings which makes me even more despair.
First I created several new maven projects but only one of them can be exported as a jar file. You can have a look a the pictures. I named them as 'working project ...', where you can see the project files, the compiled output, and the successful exportable jar process. 
**But** when I copy this working project in an other folder an try to export the project there it isn't working anymore. I got these issues: 
- `Error: Maven executable not found.`
- `DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`
- `workbench.desktop.main.js:3183 Command 'Java: Export Jar...' resulted in an error (command 'java.view.package.exportJar' not found)`

For me it seams that the Maven executable is the problem. But I have no clue how to fix it :/

**Comment by jdneo** [comment]
Thank you for your screenshot, I guess I know what's wrong here.

Could you try to expand your `Java Project` view, wait for it showing the content, and then trigger the export jar command again?

I guess it's because the extension is not activated so the command is not found.
