### ISSUE TITLE
Project Manager did't not working propertly in multi module project

### ISSUE THREAD

**Issue by yukinami** [microsoft/vscode-java-dependency#438]
I have a multi module project built with gradle. The project manager displays the modules but does not show anything under them. 

<img width="464" alt="截屏2021-01-07 下午10 46 15" src="https://user-images.githubusercontent.com/3241464/103905936-35f2f500-513a-11eb-804a-39beea700141.png">

**Comment by jdneo** [comment]
I guess it's duplicated with https://github.com/microsoft/vscode-java-dependency/issues/424.

The fix should be released in the next version. If you find the problem still exists, please feel free to comment here to let me know.

Thanks.

**Comment by AielloChan** [comment]
Any progress?
