### ISSUE TITLE
retain previous Exported elements

### ISSUE THREAD

**Issue by gahisee** [microsoft/vscode-java-dependency#449]
Issue Type: <b>Feature Request</b>

When exporting project to a jar, selected elements or libraries are not retained. I have to re-select or unselect items each time I export.

Extension version: 0.17.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.8.0-38-generic

**Comment by CsCherrYY** [comment]
Currently the custom task is supported to select or unselect items and save the configuration as a task when exporting jar. You can see the guide [here](https://github.com/microsoft/vscode-java-dependency/wiki/Export-Your-Project-to-a-Jar#advanced-custom-export-task). Does it meet your request?

**Comment by wansleynery** [comment]
This above step doesn't worked for me 'cause it just automatizates the build. For each time I am trying to rebuild jar manually, the destination jar file increases almost twice, with the same dependencies in all builds. 
![image](https://user-images.githubusercontent.com/42624198/106757187-d2f85f00-660e-11eb-82ba-33477beed73c.png)
![image](https://user-images.githubusercontent.com/42624198/106756931-8c0a6980-660e-11eb-96da-a171b03cb5eb.png)
![image](https://user-images.githubusercontent.com/42624198/106757066-b3f9cd00-660e-11eb-8269-0f4819b18c1b.png)
![image](https://user-images.githubusercontent.com/42624198/106757350-fcb18600-660e-11eb-98e4-f79879cfb7c4.png)

**Comment by CsCherrYY** [comment]
@wansleynery Is this issue appear when you are using custom task or just click `export jar` button on the title of `Java Projects` view multiple times?

**Comment by wansleynery** [comment]
It's happen when I'm using the standard option only (first image), without none custom tasks.

**Comment by CsCherrYY** [comment]
> It's happen when I'm using the standard option only (first image), without none custom tasks.

Is your exported jar file in the same folder as the source file `*.java`?

**Comment by wansleynery** [comment]
![Peek 2021-02-04 15-15](https://user-images.githubusercontent.com/42624198/106937030-09f86e80-66fc-11eb-981f-f4eb64e65a76.gif)

**Comment by jdneo** [comment]
@wansleynery This is a bug beyond this issue's topic, I moved the discussion to #452
