### ISSUE TITLE
The jar file size doubled each time when exporting jar from the navigation bar

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-dependency#452]
Copied from: https://github.com/microsoft/vscode-java-dependency/issues/449

This above step doesn't worked for me 'cause it just automatizates the build. For each time I am trying to rebuild jar manually, the destination jar file increases almost twice, with the same dependencies in all builds. 
![image](https://user-images.githubusercontent.com/42624198/106757187-d2f85f00-660e-11eb-82ba-33477beed73c.png)
![image](https://user-images.githubusercontent.com/42624198/106756931-8c0a6980-660e-11eb-96da-a171b03cb5eb.png)
![image](https://user-images.githubusercontent.com/42624198/106757066-b3f9cd00-660e-11eb-8269-0f4819b18c1b.png)
![image](https://user-images.githubusercontent.com/42624198/106757350-fcb18600-660e-11eb-98e4-f79879cfb7c4.png)

_Originally posted by @wansleynery in https://github.com/microsoft/vscode-java-dependency/issues/449#issuecomment-772531392_

**Comment by jdneo** [comment]
Copied from: https://github.com/microsoft/vscode-java-dependency/issues/449#issuecomment-773509319

![Peek 2021-02-04 15-15](https://user-images.githubusercontent.com/42624198/106937030-09f86e80-66fc-11eb-981f-f4eb64e65a76.gif)

**Comment by CsCherrYY** [comment]
@wansleynery That's probably the exported jar is nested with itself. I think custom task can solve this issue. You can follow the [Advanced: Custom Export Task](https://github.com/microsoft/vscode-java-dependency/wiki/Export-Your-Project-to-a-Jar#advanced-custom-export-task) and try to add a rule `"!${compileOutput}/${workspaceFolderBasename}.jar"` in the `elements` property of the task definition to exclude the output jar itself , like this:
```
"elements": [
  ...
  "!${compileOutput}/${workspaceFolderBasename}.jar",
  ...
],
```

**Comment by wansleynery** [comment]
Still doesn't working

VS Code: Version 1.53.0
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T15:56:04.185Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.70-amd64-desktop
Extension: vscjava.vscode-java-dependency (v0.17.0)

![Peek 2021-02-05 09-09](https://user-images.githubusercontent.com/42624198/107075253-a12af800-67c8-11eb-8e0f-dd933b5281ae.gif)

**Comment by CsCherrYY** [comment]
Since you're using custom task to export jar, you should run task by clicking `Terminal -> Run Task -> Java`, you will find your custom task by the label which is defined in the `label` property of the `tasks.json`.

**Comment by jdneo** [comment]
@wansleynery Is the problem still there if you follow @CsCherrYY's [suggestion](https://github.com/microsoft/vscode-java-dependency/issues/452#issuecomment-780987781) ?

**Comment by wansleynery** [comment]
Yes. I got this solution by hard way. I though that could do it by the easy way, but this is not the business logic of this extension. Thanks for the support!

**Comment by jdneo** [comment]
good to know the problem has been solved. @CsCherrYY please also consider how we can improve this when you have time.
