### ISSUE TITLE
Can't auto refresh when delete package from Java Project Explorer.

### ISSUE THREAD

**Issue by chenyuanmac** [microsoft/vscode-java-dependency#458]
Environment:

OS: Win
Vscode: 1.53.0
Vscode java project manager: 0.18.0

Actual Behaviour:

Can't auto refresh when delete package from Java Project Explorer.
![image](https://user-images.githubusercontent.com/70991161/107169357-9ce52180-69f8-11eb-8627-393e767597b5.png)

**Comment by jdneo** [comment]
Currently we are only watching files under `src/`
