### ISSUE TITLE
Error "No workspace folder found, please open a folder into the workspace first."

### ISSUE THREAD

**Issue by veredcon** [microsoft/vscode-java-dependency#464]
Hi,

We are installing the Java Dependency 0.18.0 extension on a theia based IDE and we get the following error:
"Java Projects: No workspace folder found, please open a folder into the workspace first."

Few notes:
1. I could not see in the code from where it is thrown.
2. I can see the "Java Projects" view although no workspace folder is opened
3. I cannot really debug the code as when debugging it on theia - I open a workspace folder with this extension code

![image](https://user-images.githubusercontent.com/9718939/109497074-32288280-7a9a-11eb-9c35-08513122f6d9.png)

Can you please assist how to remove this error message?

Thanks

**Comment by jdneo** [comment]
Hi @veredcon,

This message occurs when there is no workspace folder opened. Fortunately, we just fixed it in https://github.com/microsoft/vscode-java-dependency/pull/461 just a few days ago.

The new release containing the fix should be available in this week. I'm closing this issue since it has been fixed. 😃

**Comment by veredcon** [comment]
Great @jdneo ! Thanks for the update :)

**Comment by veredcon** [comment]
Hi @jdneo , Do you have estimation when 0.18.1 will be available in:
https://open-vsx.org/api/vscjava/vscode-java-dependency/ ?
We are waiting for this patch. 
Thanks!

**Comment by jdneo** [comment]
I have no idea for that. Currently we only publish the extension to the VS Code marketplace. Do you know who is responsible for publish this extension to open-vsx?

**Comment by veredcon** [comment]
I don't know, I thought you are publishing it there also
I can see 1.18.0 is there so it seems to be frequently updated... we have to consume it from open-vsx from legal reasons. We cannot consume it from VSCode marketplace
