### ISSUE TITLE
The Java Projects section in the Explorer menu should ignore .DS_Store files on MacOS

### ISSUE THREAD

**Issue by trevorkerney** [microsoft/vscode-java-dependency#472]
.DS_Store is a hidden file (even when hidden files are shown) related to the file system structure on MacOS's Finder. It should not be shown here.

<img width="360" alt="Screen Shot 2021-03-16 at 6 41 53 PM" src="https://user-images.githubusercontent.com/31868802/111393884-9d23ad00-8687-11eb-8557-a4ef9448fdc1.png">

**Comment by jdneo** [comment]
Thanks for reporting the issue, it's duplicated with https://github.com/microsoft/vscode-java-dependency/issues/214, so I'm closing this one.
