### ISSUE TITLE
Cannot open existing project or open new project

### ISSUE THREAD

**Issue by Penguibird** [microsoft/vscode-java-dependency#475]
After working perfectly for months, suddenly any time I open a java project, the extension doesn't recognize it and offers me to create a new one. Even if I try to create a new project it just opens the newly created project, but the extension still doesn't recognize it and doesn't let me run/build it.

I am not using any build tools like spring or maven

![image](https://user-images.githubusercontent.com/49534997/113045886-a5a7d780-919f-11eb-9757-be553ad486bd.png)

**Comment by jdneo** [comment]
@Penguibird What if you open a Java file first. And then expand the project explorer?

**Comment by Penguibird** [comment]
No, the exact same thing happens. I am mostly confident I had a java file open anyway when this occured, but tried it now and I can't get it to recognize the project.

**Comment by Penguibird** [comment]
There's not really much to see but here you are

https://user-images.githubusercontent.com/49534997/113112514-89d91b80-9209-11eb-94a6-b9a127a6e672.mp4

**Comment by jdneo** [comment]
Remove the `.classpath` and `.project` and try again?

**Comment by jdneo** [comment]
Hmm... So far I've no idea about this. Try to trigger `Java: Clean Java language server workspace`?

Or share a sample project and I can try if I can repro it locally

**Comment by jdneo** [comment]
@Penguibird What's your JDK version and the java.home setting?
