### ISSUE TITLE
Does the directory structure affect the discovery of Java Projects？

### ISSUE THREAD

**Issue by FunnyYish** [microsoft/vscode-java-dependency#493]
I found that if I had a Java Project in my subdirectory, VS Code couldn't find it。

**Comment by jdneo** [comment]
It's by design because currently the Java extension will only be activated if your project root contains Java build files: https://github.com/redhat-developer/vscode-java/blob/master/package.json#L31-L33

Will you see your project if you open a Java file contained by your project?
