### ISSUE TITLE
Java Project explorer get expanded unexpectedly when editing

### ISSUE THREAD

**Issue by arshapplied** [microsoft/vscode-java-dependency#502]
For some reason every time I run a java file, the side bar opens, highlighting the java projects panel. I really do not use the panel, since I do not find it uselful. 

I also tried to hide the panel , by right clicking on it hiding it. But every time I run a java code, it opens agains, causing my sidebar to toggle on. I do not want this. This needs to be turned off.

**Comment by jdneo** [comment]
Will take a look

**Comment by jdneo** [comment]
@arshapplied Any reason turning off the issue? Is there anything new found on your side?
