### ISSUE TITLE
Support quick locate current class file in "java projects" view

### ISSUE THREAD

**Issue by Zhan-Jie** [microsoft/vscode-java-dependency#518]
While I'm exploring a java class, sometimes I need to quickly locate its location in package hierarchy.  
In Intellij IDEA, I can click the "select opened file" icon to locate current file in the project explorer.
![image](https://user-images.githubusercontent.com/15642973/121646641-1cc6e980-cac8-11eb-9370-674b59d548c4.png)
Can you make some improvement for this situation?😊

**Comment by CsCherrYY** [comment]
We currently offer a setting to help you to locate the current class in the `Java Projects` view, could you check your setting `java.dependency.syncWithFolderExplorer` has been set to true or not? like this:
![setting](https://user-images.githubusercontent.com/45906942/121648421-133e8100-caca-11eb-8f3b-7a16482cabd1.png)
If the setting has been set to true, the extension will automatically reveal (or locate) the current opened Java file in the `Java Projects` view.

**Comment by jdneo** [comment]
@Zhan-Jie if you have any more questions/feedbacks, please let us know, thanks.
