### ISSUE TITLE
Blocked in "Configuring" and  "Refreshing" by the dependency "log4j-core" in pom.xml

### ISSUE THREAD

**Issue by wzh90** [microsoft/vscode-java-dependency#529]
!ENTRY org.eclipse.core.jobs 4 2 2021-07-15 15:06:32.003
!MESSAGE An internal error occurred during: "Register Watchers".
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.ls.core.internal.preferences.PreferenceManager.getPreferences()" because "manager" is null
	at org.eclipse.jdt.ls.core.internal.ProjectUtils.isVisibleProject(ProjectUtils.java:290)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.registerWatchers(StandardProjectsManager.java:418)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager$1.run(StandardProjectsManager.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

My project  blocking in refreshing:
![1626333277881](https://user-images.githubusercontent.com/15761455/125745469-0198f721-4774-48dd-b7dc-800fe9472da9.jpg)

java environment:
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Zulu16.30+15-CA (build 16.0.1+9)
OpenJDK 64-Bit Server VM Zulu16.30+15-CA (build 16.0.1+9, mixed mode, sharing)

**Comment by wzh90** [comment]
this can be repeatedly, but not for this reason.
I will create a new issue.

**Comment by wzh90** [comment]
this can be repeatedly, but not for this reason.
I will create a new issue.

**Comment by jdneo** [comment]
This extension is not responsible for importing projects.

Please open the issue in https://github.com/redhat-developer/vscode-java/issues.

Thanks.
