### ISSUE TITLE
Open the classfile under the package, an unknown error occured

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-dependency#53]
Build: 41
Platform: all

Open any class file under package in the explorers

Error in toggle developer tools:

Windwos:
![image](https://user-images.githubusercontent.com/28860891/46939599-44f0b700-d099-11e8-9ee9-07921909f3e3.png)
Mac and Linux:
![image](https://user-images.githubusercontent.com/28860891/46939765-c0526880-d099-11e8-88c1-a534360f081d.png)
Attached logs: 
[logs.txt](https://github.com/Microsoft/vscode-java-dependency/files/2478041/logs.txt)

**Comment by andxu** [comment]
the language server side will be handled later, and PackageCommand side is at https://github.com/Microsoft/vscode-java-dependency/pull/67
