### ISSUE TITLE
Gradle version

### ISSUE THREAD

**Issue by TroyLDay** [microsoft/vscode-java-dependency#542]
When vscode starts up, the project manager for java begins to build my multi-project repo in gradle. Starting several days ago, the builds were failing with a message:

	"message": "Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.0-rc-1-bin.zip'.\r\n
...
Could not find method compile() for arguments

It seems this is occuring because compile is fully deprecated with gradle 7.

The thing is, I have gradle 6.4.1 installed but for some reason, the automated project manager build is kicking off with v7 and there are now 7k+ problems due to this.

Is this something that the extension is forcing? Any ideas

**Comment by jdneo** [comment]
The project manager won't build/import your project, it's actually https://github.com/redhat-developer/vscode-java doing this.

But anyway, could you tell us which Gradle version is the one you want to enable in this project? If you want to force to 6.4.1, try to use this setting in your workspace: `java.import.gradle.user.home`
