### ISSUE TITLE
在导出jar的时候怎么样才能包含资源文件

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [microsoft/vscode-java-dependency#561]
我在和src目录同级创建了一个resources的文件夹,然后子目录为 resource/com/aa/data.png 

到导出jar的时候没有data.png到 com/aa目录中,怎么样才能把资源包含进去

**Comment by jdneo** [comment]
@CsCherrYY Please help take a look

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> @CsCherrYY Please help take a look

已经解决了谢谢,直接包含在对应的代码路径中就可以
