### ISSUE TITLE
Feature Request: Ability to export JAR with only single element.

### ISSUE THREAD

**Issue by nathan130200** [microsoft/vscode-java-dependency#577]
Every time i wanna export my JAR i need set manulla to export ONLY bin that is compiled code.

![image](https://user-images.githubusercontent.com/14365254/147386747-5143abd9-8219-4003-9664-f8840815fca3.png)

I didn't found any setting that i can skip referenced libraries from jar exporting. I make minecraft server plugins, everytime i need fast export to restart my server but i need manually click to export and unselect dependency that i DONT need.

Can you please implement an way to define to ignore specific libraries?

**Comment by CsCherrYY** [comment]
We support customizing the export elements via VS Code Task. You can see https://github.com/microsoft/vscode-java-dependency/wiki/Export-Your-Project-to-a-Jar#advanced-custom-export-task for the reference.

**Comment by nathan130200** [comment]
Omg, thanks, this will be very helpful.
