### ISSUE TITLE
Do not load my project, still loading infinitive mode

### ISSUE THREAD

**Issue by rafaelgimenes** [microsoft/vscode-java-dependency#578]
I'm trying to load a simple java project, it was worked before.
and Now the VScode / Project Manager do not load the "Java Project"

![image](https://user-images.githubusercontent.com/9700683/148097865-486008fd-53eb-4124-b797-516b4712745a.png)
![image](https://user-images.githubusercontent.com/9700683/148097918-e9aac469-8171-43b9-9091-e1223ca0091b.png)

the settings.json 

`{
    "java.project.sourcePaths": [
        "src"
    ], 
    "java.configuration.runtimes": [
      {
        "name": "JavaSE-1.8",
        "path": "/usr/lib/jvm/java-8-openjdk-armhf/",
        "default": true
      },
      {
        "name": "JavaSE-11",
        "path": "/usr/lib/jvm/java-11-openjdk-armhf/"
        
      }
    ],
    "JAVA_HOME":"/usr/lib/jvm/java-11-openjdk-armhf/"
}`

also I tried "java.home", anyway I cant run the java ,

![image](https://user-images.githubusercontent.com/9700683/148098767-312996bd-7aa8-42fe-90a3-b80b7ed79777.png)

**Comment by jdneo** [comment]
The spinning icon in the status bar means that the Language Server is activating. What will you see if clicking on it?

**Comment by rafaelgimenes** [comment]
when I click in the circle this screen is appear
![image](https://user-images.githubusercontent.com/9700683/148209805-a5008470-5eb9-46bd-8f9a-1e208c20037a.png)

**Comment by jdneo** [comment]
How about the server log? You can check it by triggering the command `Java: Open Java Language Server Log`
