### ISSUE TITLE
How setting about javadoc and resource?

### ISSUE THREAD

**Issue by nightmare-mio** [microsoft/vscode-java-dependency#586]
# I can‘t see javadoc and resource on vscode of maven project
![1](https://user-images.githubusercontent.com/52735303/150646619-b0f81ecf-bd10-4b9b-9e28-c9c42caa7e31.jpg)
![2](https://user-images.githubusercontent.com/52735303/150646645-a7fd70b0-ec45-4e0e-9ac2-0ced3240494e.jpg)
## but I hava javadoc and resource
![3](https://user-images.githubusercontent.com/52735303/150646680-866a65eb-7c05-4cca-a19b-b12917551a77.jpg)

**Comment by jdneo** [comment]
@nightmare-mio What if you close the editor tab: `DynamicRegistrationBean.class`, reload the VS Code?

**Comment by nightmare-mio** [comment]
老样子,
The same as usual.

**Comment by nightmare-mio** [comment]
oh,today is ok.

**Comment by jdneo** [comment]
@nightmare-mio

It's because the setting `java.maven.downloadSources` by default is false. Which means by default, the source jar will only be downloaded when you have open the class file at least once.

And before the source jar is downloaded, only stub source will be displayed.
