### ISSUE TITLE
Duplicated tree nodes in Java Projects view

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-dependency#588]
![image](https://user-images.githubusercontent.com/14052197/150733449-d196afe0-93cb-47fe-94d2-7c68dfbc4758.png)

**Comment by jdneo** [comment]
Looks like a concurrent issue when multiple invocation of `reveal()` happens at the same time:

https://github.com/microsoft/vscode-java-dependency/blob/ac162dac91836aa065e07782a06880e624938004/src/views/dependencyExplorer.ts#L143
