### ISSUE TITLE
Unable to remove external jars from Referenced Libraries in JAVA PROJECTS

### ISSUE THREAD

**Issue by cosmicblip** [microsoft/vscode-java-dependency#589]
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Issue**
I am unable to delete/remove the external jars that I have added ( see below)
![image](https://user-images.githubusercontent.com/89976050/151665525-be53dce8-0876-461e-b164-dbc4f6d5e879.png)

I have also tried exluding it from the settings.json 

```
{
    "java.project.referencedLibraries": {
        "include": [
            "lib/**/*.jar",
            "c:\\Users\\<username>\\Downloads\\external-jars\\some.jar"
        ],
        "exclude": [
            "c:\\Users\\<username>\\Downloads\\someDirectory\\someDirectory\\someJar.zip",
            "c:\\Users\\<username>\\Downloads\\someDirectory\\someDirectory\\someJar.jar",
           
        ]
    }
}
```
But still I am unable to remove it.

I have tried the following 
- Uninstalled VS Code 
- Deleted Code Folder 
- Deleted .vscode with extensions. 

Can you please provide the right solution, and for the short term can you point to the cache or local directory where this config might be saved so that I can delete it from there.

**Comment by jdneo** [comment]
Currently removing/adding a referenced jar from Maven project is not supported, see: https://github.com/microsoft/vscode-java-dependency/issues/218. You need to directly edit the classpath entries in the `.classpath` file of your project.

I'm closing this issue since we have an existing one to track this. But feel free to ask questions if you have.

**Comment by cosmicblip** [comment]
Thanks @jdneo but I tried editing in .classpath but it does not show any Referenced libraries in the first place.
Plus it is read only , am referring the correct .classpath ? Please let me know if there is some other file location to edit.
![image](https://user-images.githubusercontent.com/89976050/151709786-2688dcf0-9c52-46a4-957a-6307360b7876.png)

**Comment by jdneo** [comment]
Ah, I mean there should be a file called `.classpath` at your project root. Could you see it?

**Comment by Marinell0** [comment]
I have the same issue but `.classpath` does not exist on my project.

**Comment by jdneo** [comment]
@Marinell0 it's hidden by default. See: https://github.com/redhat-developer/vscode-java/blob/master/document/_java.metadataFilesGeneration.md

**Comment by Marinell0** [comment]
Thank you, solved my problem!
