### ISSUE TITLE
Any way to include source file and ressources easily

### ISSUE THREAD

**Issue by space192** [microsoft/vscode-java-dependency#590]
Hey, so I was wondering if there is a quick and easy way to include sources and resources files in jar export ?

**Comment by space192** [comment]
Managed to find a way by modifying the task,
for anyone having the same problem as me (school requirements) here's my modified task (not optimal but it does the job)
![image](https://user-images.githubusercontent.com/44359684/152258566-1f2a75c1-e7bd-4d15-9533-101c409c9fed.png)

**Comment by jdneo** [comment]
Yes you can customize the export jar task to achieve that.

I'll close this issue since it has been resolved.
