### ISSUE TITLE
Multiple source not getting updated in bin

### ISSUE THREAD

**Issue by AdhTri001** [microsoft/vscode-java-dependency#596]
This is rather an issue or I might be doing something wrong. I am facing issue of the sources with resources not getting updated in the bin folder that is generated for launch or debug. I am using the feature introduced by #412 :
```json
"java.project.sourcePaths": [
    "src",
    "resources"
]
```
I have a resource and a src folder in the project root:
![image](https://user-images.githubusercontent.com/84070263/154762599-f3b3494b-3fad-4714-a514-b3a79f313c14.png)
I load the fxml with `getClass().getResource("fxml/App.fxml")` but all the resources are only updated when I first launch the project after reloading vscode. Is this ideal? Or is there any other better way for resource management with this extension.
Thanks for your brilliant work with the extension :)

**Comment by AdhTri001** [comment]
@CsCherrYY sorry for mentioning but looks like u r an active maintainer, could you please help?

**Comment by jdneo** [comment]
I did a quick test for this, here is what I've done:

1. explicitly set the output path to `"bin"` via the setting `java.project.outputPath` in `WORKSPACE` scope.
2. update a xml file in resource folder
3. check the content in the bin folder

What I observed is that the xml file in the bin folder is update.

Is there any difference from your case?

BTW, from your screenshot, seems that the output folder is not contained in your workspace, how do you know that it's not update?

**Comment by AdhTri001** [comment]
I myself now can't reproduce the problem. I guess what is that the file that I might be editing might be someother file. Sorry for useless issue.
