### ISSUE TITLE
Support creating new files/folders in Java Project explorer

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-dependency#598]
feedback from user survey:

_in project explorer, in Java Projects Tab I cannot create html file or folder or POM file_

**Comment by jdneo** [comment]
We can consider to integrating with the `New File...` from VS Code 1.70.0

**Comment by izilongwan** [comment]
> We can consider to integrating with the `New File...` from VS Code 1.70.0

版本都1.7.6功能都没出来

**Comment by jdneo** [comment]
It's talking about this UI entry 
![image](https://user-images.githubusercontent.com/6193897/224589914-e8846fb7-6b58-4d8a-b683-6022fdf7012a.png)
