### ISSUE TITLE
Visualize Maven / Gradle POM and property file in Java Project Explorer

### ISSUE THREAD

**Issue by raulvaldoleiros** [microsoft/vscode-java-dependency#604]
It would be great if we can add files (property files,etc) in the java projects view. If this is already implemented can you share with me how to do it?

Thanks

**Comment by jdneo** [comment]
Currently it's not supported, but it's in out backlog.

**Comment by jdneo** [comment]
Adding new file will be tracked by #598 

Visualize pom/gradle files will be tracked by #145
