### ISSUE TITLE
Create Project UI

### ISSUE THREAD

**Issue by Gaming32** [microsoft/vscode-java-dependency#605]
It would be much nicer to have a nice UI to create projects, similar to other IDEs. Currently this extension uses a step-by-step very linear process to create new projects. This means that edits cannot be made to previous fields, for example. It also means that every step has to be gone through, instead of just skipping over fields that you don't need to worry about (some kind of "Advanced" section).

**Comment by jdneo** [comment]
Hi @Gaming32, thank you for the feedback. It's a little bit complex so let me explain the problem from different parts separately.

> It would be much nicer to have a nice UI to create projects, similar to IDEs

As an extension of VS Code, it's limited to the APIs provided by the VS Code. The current behavior is the best what we can do. My personal opinion to this is: different IDEs/editors have their own philosophy about how UI/UX should look like. VS Code chooses a neat and clean way and personally I like it.

> Currently this extension uses a step-by-step very linear process to create new projects. This means that edits cannot be made to previous fields.

Actually, VS Code supports the multi-step quick picks that can go back. So it depends on whether the extensions adopt the capability. Though we have different types when creating projects, but most of them are delegated to other extensions to handle. For example, to create a Maven project, it will be delegated to the Maven extension to do the real creation. So could you let us know what kind of project you are creating? We can file an issue to request that extension to adopt the 'go-back' feature.

> every step has to be gone through, instead of just skipping over fields that you don't need to worry about (some kind of "Advanced" section)

This is a good ask (feature request). Again, could you let us know the project you are using and we can check if we can do that or it's owned by other orgnization?

**Comment by Gaming32** [comment]
I had actually meant to make the feature request on the [vscode-maven](https://github.com/microsoft/vscode-maven) repository, as that's my build tool of choice.

**Comment by jdneo** [comment]
Maven extension should already adopt the go-back capability, you can click the top-left button

![image](https://user-images.githubusercontent.com/6193897/161171186-62a6afb1-9e09-4754-bb0b-2c85d0e578ad.png)

// cc @Eskibear

**Comment by jdneo** [comment]
I'm closing this issue since according to the discussion, it's out of this extension's scope. But feel free to leave comments if you have.
