### ISSUE TITLE
"Move to recycle bin" from Java Project Explorer does not work

### ISSUE THREAD

**Issue by nickzhums** [microsoft/vscode-java-dependency#608]
Environment:

VS Code Version: 1.66.1 (Universal) 
Extension Version: 0.22.3
JDK Type & Version:  AdoptOpenJDK-11.0.11+9
OS Type & Version: linux container (ubuntu focal)

我使用vscode remote模式开发Java工程的时候, 在 “资源管理器” - “JAVA PROJECTS” 一栏中无法删除工程文件:选择 “Move to Recycle Bin”, 实际上却并没有删除, 而在目录一栏中可以右键选择 “永久删除” 来删除文件.

能在不同环境多次复现此问题, 复现步骤视频已通过微信发给您.

视频如下：
https://user-images.githubusercontent.com/56864335/162714164-4757b190-a66c-406d-bb9c-c2e9e42eab31.mp4

**Comment by jdneo** [comment]
Tried to repro it with a Windows machine but not success


https://user-images.githubusercontent.com/6193897/162864936-67d9d41a-6277-490a-834c-c6d0cf01d500.mp4

**Comment by jdneo** [comment]
Thank you. I can now reproduce it in Codespaces. Will take a look

**Comment by jdneo** [comment]
Observed following error:

'Error (FileSystemError): Unable to delete file '[vscode-remote://codespaces+xxxx]()' via trash because provider does not support it.'

**Comment by jdneo** [comment]
@lwp2070809

We've just released a fix for this issue in the `pre-release` channel. If you want to try with it. Just simply switch the extension to pre-release version:

![image](https://user-images.githubusercontent.com/6193897/163306584-b5833d74-ff32-4d6f-8898-552b86fd47b4.png)

**Comment by lwp2070809** [comment]
I have test in pre-release version and glad to see that this issue has been fixed. Thanks very much for your work! @jdneo @nickzhums

**Comment by nickzhums** [comment]
you are welcome @lwp2070809 . The kudos goes to @jdneo who fixes the issue :)

**Comment by jdneo** [comment]
To verify this issue:

1. The remove command in local should be able to remove the item and the removed item goes to the recycle bin.
2. The remove command in remote should be able to remove it and the item will be removed permanently
