### ISSUE TITLE
Support drag and drop in Project explorer

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-dependency#613]
Below are the scenarios that we can support in the first iteration:

1. Drag java project explorer node to editor:
    - [x] primary type to editor
    - [x] document symbol to editor

2. DnD inside the java project explorer:
    - [x] Move file nodes (to folder, package, package root)
    - [x] Move folder nodes (to folder, package, package root)
    - [x] Move source types (to folder, package, package root)
    - [x] Move packages (to folder, package, package root)
    - [x] Move jars into Unmanaged Folder's Referenced Libraries node

3. DnD from VS Code's file explorer and the system's file explorer
    - [x] Move jars into Unmanaged Folder's Referenced Libraries node
    - [x] Copy files into Java Projects explorer from system file explorer

**Comment by CsCherrYY** [comment]
tested in the newest pre-release (0.20.2022062500) and found an inconsistent.

![dnd](https://user-images.githubusercontent.com/45906942/176083062-95019008-6079-4c35-9cdc-192fef852698.gif)

can we also show a confirm dialog when moving members of a type?

**Comment by jdneo** [comment]
> can we also show a confirm dialog when moving members of a type?

That's a bug I think. So far we should prevent moving members. I'll take a look.
