### ISSUE TITLE
Can't open multiple projects under a folder - please help.

### ISSUE THREAD

**Issue by ghandylan** [microsoft/vscode-java-dependency#618]
![image](https://user-images.githubusercontent.com/80078209/170837658-271f0cb8-ab3d-4ef9-b62b-d17cb941df91.png)

How do I reproduce this? I am unable to open multiple java projects under a folder.

All I get is this
![image](https://user-images.githubusercontent.com/80078209/170837709-0e11af9d-43b2-4597-a45c-f8c0cab58f49.png)

**Comment by jdneo** [comment]
from the screenshot, looks like your projects are projects without build tools.

If the bellow settings are all the same for those projects:
- java.project.outputPath
- java.project.referencedLibraries
- java.project.sourcePaths
Then you can use the multi-root mode to import them: https://code.visualstudio.com/docs/editor/multi-root-workspaces.

But if the settings are different for them, than you have to open them separately in different VS Code instances. This is a limitation currently.

**Comment by jdneo** [comment]
Hi @ghandylan, is your problem solved?

**Comment by ghandylan** [comment]
> Hi @ghandylan, is your problem solved?

hello @jdneo!
yes, the issue is solved. thank you for your help 👍
