### ISSUE TITLE
When to support the Android project

### ISSUE THREAD

**Issue by mingxigao** [microsoft/vscode-java-dependency#626]
Do you have any plan to support Android Project created by Android studio?

**Comment by jdneo** [comment]
So far, there is no concrete plan for Android support.

Please check: https://github.com/redhat-developer/vscode-java/issues/1390#issuecomment-652302766

**Comment by jdneo** [comment]
See: https://github.com/eclipse/eclipse.jdt.ls/pull/2197

Code navigation and editing is supported now.
