### ISSUE TITLE
Can't create java project with gradle

### ISSUE THREAD

**Issue by 2300ms** [microsoft/vscode-java-dependency#628]
When i try to create a new java project using gradle, a popup appear, which said this `Gradle for Java is required to create Gradle projects. Please re-run the command 'Java: Create Java Project...' after the extension is installed.` But i have already this extension installed, what should i do?

**Comment by jdneo** [comment]
What the version of your extension? Is this extension being disabled?

**Comment by 2300ms** [comment]
The version is v3.6.1 and it's enable globally

**Comment by jdneo** [comment]
Please update it to at least `3.10.0`.

One wired thing, if the extension is installed but the version is lower than the requirement, you should receive a notification to update the extension but not install...

**Comment by jdneo** [comment]
Ok that seems because the extension's id has been changed after `3.6.1`.

Please make sure the id the extension you installed is `vscjava.vscode-gradle`

![image](https://user-images.githubusercontent.com/6193897/172583497-ef34dc23-4026-4ddd-b218-30f56a7da0c3.png)

**Comment by jdneo** [comment]
Close since it's inactive for a long time. Feel free to comment if you have any more questions.
