### ISSUE TITLE
I have problems running the app.

### ISSUE THREAD

**Issue by mrrynk** [microsoft/vscode-java-dependency#650]
I have problems running the app, 
can someone help me fix it.?
`PS E:\Học Tập\JAVA\hoangAnh>  e:; cd 'e:\Học Tập\JAVA\hoangAnh'; & 'C:\Users\Duck\AppData\Local\Programs\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin\java.exe' '-XX:+ShowCodeDetailsInExceptionMessages' '-cp' 'E:\Học Tập\JAVA\hoangAnh\bin' 'App' 
Error: Could not find or load main class App
Caused by: java.lang.ClassNotFoundException: App
PS E:\Học Tập\JAVA\hoangAnh> `

![image](https://user-images.githubusercontent.com/9208169/175926859-9f862484-0167-49cb-b94e-8036a0219644.png)

**Comment by jdneo** [comment]
Is `App.class` exists in the `bin` folder?

@testforstephen

**Comment by jdneo** [comment]
Close due to being inactive.

You can still comment here when you have more information to share.
