### ISSUE TITLE
Projects which have linked resources is not supported well.

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode-java-dependency#654]
I'm currently trying to integrate https://github.com/jbangdev/jbang-eclipse with jdt.ls, which kinda worsS, but I noticed the Java Projects view doesn't show the JBang classpath container defined in https://github.com/jbangdev/jbang-eclipse/blob/main/dev.jbang.eclipse.core/plugin.xml#L38. In Eclipse it looks like: 

![](https://user-images.githubusercontent.com/148698/174653463-39ea956f-cba8-40d7-8cbf-0d3b50cf49c1.gif)

The label is defined in https://github.com/jbangdev/jbang-eclipse/blob/main/dev.jbang.eclipse.core/src/main/java/dev/jbang/eclipse/core/internal/classpath/JBangClasspathContainer.java#L26, but I don't know if there's an easy way to get to that, using JDT's API.

In any case, not showing the dependencies at all is very annoying.

![Screenshot 2022-06-28 at 20 05 43](https://user-images.githubusercontent.com/148698/176252174-e660aa8b-74a4-4f08-982d-0d0be230fb5c.png)

**Comment by jdneo** [comment]
Is there any steps to play with it?

Looks like related with https://github.com/microsoft/vscode-java-dependency/blob/main/jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java#L258. Need a sample to debug.

**Comment by fbricon** [comment]
See attached extension and demo file: [jbang-demo.zip](https://github.com/microsoft/vscode-java-dependency/files/9008084/jbang-demo.zip)
- unzip and install vsix
- open jbangscript folder
- open hello.java

You should see a JBang Discovery build step in the Java status
This is still highly experimental, there are some issues with the JBang builder so you might see some compilation errors. Try deleting / re-adding the `//DEPS com.github.lalyos:jfiglet:0.0.9` line (or change version to 0.0.8 or lower)

There might be some conflicts between the Java version configured for the invisible project, vs the java version configured by the `//JAVA` comment, but that's another issue.

**Comment by fbricon** [comment]
You should be able to get the proper label of any classpath container from 

IClasspathContainer container = JavaCore.getClasspathContainer(classpathEntry.getPath(), javaProject);
return container.getDescription()

**Comment by jdneo** [comment]
Still investigating the issue. Some findings:

After import the sample project, there are two projects imported:
- `hello.java` - The JBang project
- `jbangscript_xxxxx` - The invisible project

When passing the proejct folder `jbangscript`'s uri to the code here https://github.com/microsoft/vscode-java-dependency/blob/6d48fade62326f209517dc5b56512d0289ba27e3/jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/PackageCommand.java#L615

returns the invisible project, which does not contain the JBang classpath entry.

**Comment by fbricon** [comment]
try adding `-Dm2e.discovery.url=https://download.eclipse.org/technology/m2e/discovery/directory-1.13.xml` to your eclipse.ini

**Comment by jdneo** [comment]
Still see multiple projects imported in the workspace storage. I installed the vsix in the latest zip file and cleaned the workspace cache.

![image](https://user-images.githubusercontent.com/6193897/176576557-1f7d2cf2-b01a-40b0-97a2-562288de8f4b.png)

Anyway, since the uri passed to the Java code is the folder opened in VS Code, and that's a linked folder of the invisible project, so the current implementation is not aware of the imported JBang project in the workspace cache. Looks like we need to introduce some new strategies to handle this kind of (not only for JBang) situation.

**Comment by fbricon** [comment]
No it shouldn't generate the invisible project. Make sure you delete ~/Library/Application Support/Code/CachedExtensionVSIXs before installing the vsix

**Comment by jdneo** [comment]
Root cause found:

It's here https://github.com/microsoft/vscode-java-dependency/blob/6d48fade62326f209517dc5b56512d0289ba27e3/jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java#L110-L111 We limit to only support invisible project when the project uri is out of the workspace.

**Comment by fbricon** [comment]
I've published the code to my extension to https://github.com/fbricon/vscode-jbang. Updated vsix can be found in https://github.com/fbricon/vscode-jbang/releases/tag/latest

**Comment by jdneo** [comment]
Thanks for the update @fbricon. Will take a look when I have time :)

**Comment by fbricon** [comment]
And pre-releases are now available on https://marketplace.visualstudio.com/items?itemName=jbangdev.jbang-vscode
