### ISSUE TITLE
Tests in created gradle project fail with java.lang.SecurityException

### ISSUE THREAD

**Issue by kriber82** [microsoft/vscode-java-dependency#656]
I created a gradle project using the Create Java Project command from the command palette
When executing a gradle build, the test task failed.
The following inner exception was thrown: Caused by: java.lang.SecurityException: Prohibited package name: java.gradle
This was caused by the package name (java.gradle) that was used for the generated classes App and AppTest
When changing the package name for both classes, the gradle build executes without errors

Visual Studio Code Version: 1.68.1 (user setup)

Extensions: 
Project Manager for Java v0.20.0 (from Extension Pack for Java v0.23.0)
Gradle for Java v3.12.1

JDK (preset from Extension Pack Setup):
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

**Comment by CsCherrYY** [comment]
You should not use `java` as a segment of a package name. Changing to another name would solve this issue.

**Comment by kriber82** [comment]
I know that I should not use java as part of a package name.
Maybe I didn't make it clear enough that this package name was generated by the "Create Java Project" (with gradle) command from the command palette. As far as I could determine, this command is part of your  VS-Code plugin "Project Manager for Java"

**Comment by CsCherrYY** [comment]
Actually the project creation behavior is delegated to `Gradle for Java` extension. It will not check your package name since Gradle itself won't do such thing. you can verify it via CLI command `gradle init` to create a new project.

**Comment by jdneo** [comment]
@kriber82 if you have more questions about creating Gradle projects, feel free to file issues at https://github.com/microsoft/vscode-gradle/issues.

Thanks.
