### ISSUE TITLE
Add support for closing/ignoring workspace folders

### ISSUE THREAD

**Issue by martin-juhlin** [microsoft/vscode-java-dependency#666]
I have created a workspace with two folders, a java project and my global Go language folder "~/go". Unfortunately when playing around with go language and antlr parsing generator, there is now .java files inside the ~/go folder that doesn't have a proper project structure and doesn't compile. As I'm new to Java in VSCode, I have no idea how to get VSCode to ignore this files and I have now constant errors in the "Problems" view.

To me it would be very helpful that the popup menu in "Java projects" view also included a "ignore path" / "exclude path" option to get VSCode to ignore everything java related in my Go language folder.

**Comment by jdneo** [comment]
The vscode-java extension has a setting `java.import.exclusions`. Maybe that could be a way to exclude the go project. You can set it in the WORKSPACE scope.

**Comment by jdneo** [comment]
Close since being inactive. Please feel free to leave comments if you have any update. :)
