### ISSUE TITLE
Referenced libraries

### ISSUE THREAD

**Issue by 46578** [microsoft/vscode-java-dependency#668]
Issue Type: <b>Bug</b>

在no build tools的情况下创建项目，添加referenced libraries后就无法运行和调试

Extension version: 0.20.0
VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by jdneo** [comment]
请提供更多信息帮助我们理解问题，可以是一个sample project，或者截图/录频
