### ISSUE TITLE
extension not activated when I open a spring guide repo

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-java-dependency#680]
Repo:
https://github.com/spring-guides/gs-testing-web

The repo actually includes two spring projects (intial, complete). The guide teaches you how to start from the `initial` project and make it `complete`  by adding pieces of code like controllers,etc..

When I open the repo directly, Java extension/Maven extension/Spring extensions are all activated. But this extension is not activated (not listed in running extensions) and I cannot see the "Java Projects" view. It's to some extent wired. After I open any .java file, it gets back to normal.  Open for discussion whether we need to fine-tune activation events.

After opening the repo:

![image](https://user-images.githubusercontent.com/2351748/181700205-1ed33131-508d-414a-bcb1-921ce0de59a7.png)

After opening a .java file:

![image](https://user-images.githubusercontent.com/2351748/181700267-d8deaf2a-5776-4310-b40d-e922ee3fd7d9.png)

**Comment by jdneo** [comment]
Looks like we need to align with https://github.com/redhat-developer/vscode-java/pull/2554
