### ISSUE TITLE
add to referenced libraries working with Java project remote

### ISSUE THREAD

**Issue by nbys** [microsoft/vscode-java-dependency#702]
I work on a Java project on a remote VM via Remote-SSH extension. It looks like it is not possible to add an external Jar file in the project manager while working on a remote host. There is no + icon in UI near to Referenced Libraries. Also, the configuration in settings.json seems to have no effect as well:
```json
"java.project.referencedLibraries": [
    "library/**/*.jar",
    "/home/username/lib/foo.jar"
]
```

**Comment by jdneo** [comment]
Are you working on a project without any build tools?  - No maven, gradle and not eclipse.

**Comment by nbys** [comment]
@jdneo it is Spring project builded by Gradle. You could easy simulate this: try to create a [Dev Container](https://code.visualstudio.com/docs/devcontainers/containers) with a Gradle-based project. Then, try to add some external jar file to external dependencies.

**Comment by jdneo** [comment]
Ok, the referenced libraries are not supposed to work with Gradle project now. It's for the project without build tools. (We call it unmanaged folders).

Your request is the same as https://github.com/microsoft/vscode-java-dependency/issues/218. Let's track it there.
