### ISSUE TITLE
Support creating Micronaut projects

### ISSUE THREAD

**Issue by dbalek** [microsoft/vscode-java-dependency#713]
Consider adding a support for creating Micronaut projects to the 'Java: Create Java Project...' command.
Micronaut projects can be created by calling the 'extension.micronaut.createProject' command provided by the GraalVM Tools for Micronaut ('oracle-labs-graalvm.micronaut') extension.
For more information on Micronaut, see https://micronaut.io/.
Thanks.

**Comment by jdneo** [comment]
Fixed by #757
