### ISSUE TITLE
"java.import.generatesMetadataFilesAtProjectRoot" is not honored

### ISSUE THREAD

**Issue by anandbibek** [microsoft/vscode-java-dependency#716]
I've set the property "java.import.generatesMetadataFilesAtProjectRoot" to TRUE in user settings, remote settings, workspace and even at folder level. Tested in local env as well as on remote. Could never get it to work.

I wanted the .classpath and .project folders to be created in root directory for easier access.

**Comment by anandbibek** [comment]
Bit confused if it's the right place though.

**Comment by jdneo** [comment]
This extension is only responsible for displaying the `Java Project` explorer.
