### ISSUE TITLE
Support having multiple unmanaged folder projects in one workspace

### ISSUE THREAD

**Issue by ipsfsw** [microsoft/vscode-java-dependency#718]
After using this plugin to create a no build project Project, you can not change the opening mode of the created project. We want to modify the Project Open Behavior similar to the Maven for java plugin, and add a behavior to open the project after creating the project.
Multi-root project seems to be supported, there is no option to open it.

**Comment by jdneo** [comment]
Do you mean ask user how to open it? (in new window or current workspace?)

No build tool project now has some problems in the multi-root workspace. In other words, now, each workspace could only have one no build tool project.

**Comment by ShenZhisong** [comment]
Yes, I mean implement support for multiple projects without build tools in one workspace and add a way to ask users to open new projects. If multiple root projects are not supported, the query is unnecessary.

Thank you for your answer.
