### ISSUE TITLE
java proejcts功能缺陷

### ISSUE THREAD

**Issue by izilongwan** [microsoft/vscode-java-dependency#724]
<img width="292" alt="image" src="https://user-images.githubusercontent.com/48234072/224478684-8abc9ccc-7150-43a5-9a96-3b68d2056fb0.png">

无法创建文件夹和文件
无法创建resources下的资源
没有显示pom文件

**Comment by jdneo** [comment]
Duplicated with https://github.com/microsoft/vscode-java-dependency/issues/598, https://github.com/microsoft/vscode-java-dependency/issues/604, https://github.com/microsoft/vscode-java-dependency/issues/145
