### ISSUE TITLE
The display of the jar under library is not expected on Windows

### ISSUE THREAD

**Issue by lxhmavis** [Microsoft/vscode-java-dependency#74]
Build: 44
Vscode1.28.2
JDK10.0.2

Open the simple java project, the jar under library as below:
![image](https://user-images.githubusercontent.com/41565966/47137731-07cf3380-d2ea-11e8-8c51-7182bde05a4d.png)
Mac-expected:
![image](https://user-images.githubusercontent.com/41565966/47138453-03a41580-d2ec-11e8-9930-aa6b046f22d1.png)

and the eclipse on Windows is that:
![image](https://user-images.githubusercontent.com/41565966/47137813-4664ee00-d2ea-11e8-8938-43f114d506d6.png)

**Comment by andxu** [comment]
jdk 11 issue, should be dup as https://github.com/Microsoft/vscode-java-dependency/issues/121
