### ISSUE TITLE
VSCode presents dependency error, however, mvn install works in the terminal

### ISSUE THREAD

**Issue by felipemmasan** [microsoft/vscode-java-dependency#746]
Type: <b>Bug</b>

When I try to open a java project in VSCode, through WSL2. The project is open, but errors are presented in the POM, stating that it is not possible to resolve the dependencies of my private repository.

The problem is that by using the mvn clean install command, through the terminal it runs successfully.

I checked and the configuration in VSCode is correct, pointing to the right path of settings.

If I try to open the same project, other than through WSL2, the project opens correctly without problems.

Extension version: 0.21.2
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.82GB (2.22GB free)|
|Process Argv|--crash-reporter-id 7930ed2c-585c-476e-9e24-6306764a5674|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|7.67GB (5.97GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30705553
pythonb192cf:30669361
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by jdneo** [comment]
Could you confirm that your WSL2 has access to your private repo?

**Comment by felipemmasan** [comment]
> Could you confirm that your WSL2 has access to your private repo?

Yes As I said. when i run the mvn clean install command, it runs successfully. I can even check in wsl, the files downloaded in the local repo after executing the command

**Comment by jdneo** [comment]
Do you have some special settings in your user settings.xml? If yes, try: `java.configuration.maven.userSettings`

**Comment by felipemmasan** [comment]
> Do you have some special settings in your user settings.xml? If yes, try: `java.configuration.maven.userSettings`

yes, it is already configured for my settings

**Comment by jdneo** [comment]
I've no idea why it's not working. Would be helpful if some detailed reproduce steps can be provided.

**Comment by felipemmasan** [comment]
> I've no idea why it's not working. Would be helpful if some detailed reproduce steps can be provided.

The steps I did were:
- Install WSL2, Ubuntu
- Configure Maven and JDK in WSL
- Configure the settings file in WSL, with data from my private repository, where my dependencies are
-Clone any project that has dependencies that only exist in my private maven repository.
- run the MVN clean install command on WSL. In this step, the execution is successful, that is, the dependencies were identified during the execution

With these steps I ensured that WSL was correctly configured with Maven and the JDK.

After this:
- Open VSCode via WSL.
- Opened the project that I cloned in WSL
- With the project open, the dependencies that only exist in my private repository, are not identified and marked with error in VSCode.
- To ensure that everything was correct, I opened the vscode terminal (on the same screen that already had the project open) and, through this terminal, executed the command mvn clean instal. The command was executed successfully.

Following all these steps, I conclude that the configuration in WSL is correct, is something missing in VSCode.

In VSCode, I set the maven settings path correctly. I put the path where it is stored in WSL

**Comment by jdneo** [comment]
Not sure if it's a problem of the m2e (component used to import Maven project). This extension is not responsible for importing Maven project, so I filed an issue to the upstream project repo. Let's wait and see the response.

**Comment by snjeza** [comment]
@felipemmasan could you try to set `java.configuration.maven.globalSettings`?

**Comment by felipemmasan** [comment]
> @felipemmasan could you try to set `java.configuration.maven.globalSettings`?

I already did this configuration and it didn't work..

I put the path of my settings file which is available in WSL.

**Comment by snjeza** [comment]
> I put the path of my settings file which is available in WSL.

Could you show your settings.json or `java.configuration.maven.globalSettings`?

**Comment by felipemmasan** [comment]
> > I put the path of my settings file which is available in WSL.
> 
> Could you show your settings.json or `java.configuration.maven.globalSettings`?

I reconfigured the entire environment and put the configuration of the java.configuration.maven.globalSettings variable again and it worked.

I think I must have missed something the first time I set it up.

Thanks to all for your help...
