### ISSUE TITLE
Display the dependency info for the vscode-java default project

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-dependency#75]
It's better to show the dependency info for the default project.

**Comment by andxu** [comment]
Will show the default when the language server side finishes

**Comment by akaroml** [comment]
our plan is to get rid of the default project. so let's hold this.

**Comment by yaohaizh** [comment]
Revisit this issue since we already have invisible project supports.
In this case:
1. Not support dependency for default project.
2. Support dependency for default project & invisible projects.

**Comment by jdneo** [comment]
Current behavior:

Invisible project is supported. 
Default project is not supported.
