### ISSUE TITLE
Support manage the dependencies in single file project

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-java-dependency#76]
One use case is to run single file tests.

See: https://github.com/Microsoft/vscode-java-test/issues/348

**Comment by yaohaizh** [comment]
Supported on the latest version by default.

**Comment by maddy302** [comment]
Hey, I am trying to view the tests in the "Test" , but I see no tests, though I have few jUnit and the sample project from [discussion](https://github.com/microsoft/vscode-java-test/files/3323540/javatest.zip).

I have VSCode July V 1.37, "Java Test Runner" extension installed. Do you have any reference, using which I can configure my workspace?

**Comment by yaohaizh** [comment]
@jdneo

**Comment by jdneo** [comment]
@maddy302 Moved to https://github.com/microsoft/vscode-java-test/issues/776
