### ISSUE TITLE
java projects view remains empty, error popup appears

### ISSUE THREAD

**Issue by SLepUbIn** [microsoft/vscode-java-dependency#763]
When tring to unfold the java projects view with extension v0.22.0, a popup appears with the message : 

"no delegateCommandHandler for java.project.checkImportStatus"

![Screenshot_20230510_094036](https://github.com/microsoft/vscode-java-dependency/assets/21307859/37173300-38e0-426a-a3c6-67aa14fdd82b)

Java projects is empty : 

![Screenshot_20230510_094059](https://github.com/microsoft/vscode-java-dependency/assets/21307859/4f3109d7-8ee0-4522-8189-e1fd64421723)

Cleaning workspace and server space does not help.
Restarting code neither.

Also you can find logs attached

[vscode.log](https://github.com/microsoft/vscode-java-dependency/files/11439622/vscode.log)

Reverting the extension to 0.21.2 fixes the issue.

**Comment by jdneo** [comment]
Wait, is VS Code OSS use the same marketplace of VS Code?

**Comment by SLepUbIn** [comment]
Yes it uses the same marketplace.
It is the version bundled by the linux distribution manjaro.

I tried to delete folder /home/ubik/.vscode-oss/extensions/vscjava.vscode-java-dependency-0.22.0-universal/ and reinstall, same problem.

I looked in the new ly created /home/ubik/.vscode-oss/extensions/vscjava.vscode-java-dependency-0.22.0-universal/ folder and there is no server subfolder in it.

When I look at the /home/ubik/.vscode-oss/extensions/vscjava.vscode-java-dependency-0.21.2-universal/ folder , there is a server subfolder with the jar in it.

```
~/.vscode-oss/extensions/vscjava.vscode-java-dependency-0.21.2-universal/server
❯ ls
com.microsoft.jdtls.ext.core-0.21.2.jar
```


```
~/.vscode-oss/extensions/vscjava.vscode-java-dependency-0.22.0-universal
❯ ls
CHANGELOG.md  icons        logo.png  package.json      package.nls.zh-cn.json  README.md    templates
dist          LICENSE.txt  main.js   package.nls.json  package.nls.zh-tw.json  SECURITY.md  ThirdPartyNotices.txt
```

**Comment by jdneo** [comment]
This is the link where you can download 0.22.0 from the official marketplace. I verified that the server folder exists in the downloaded vsix: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vscjava/vsextensions/vscode-java-dependency/0.22.0/vspackage

Your extension must be downloaded from open vsx: https://open-vsx.org/extension/vscjava/vscode-java-dependency

I checked the content of the vsix, the server folder is not there.

As a workaround, you can manually install the extension downloaded from the official marketplace and file an issue at https://github.com/eclipse/openvsx to report this problem.

**Comment by amvanbaren** [comment]
@SLepUbIn, @jdneo The Open VSX server does not remove any files or folders from the VSIX package.

**Comment by jdneo** [comment]
@amvanbaren How does Open VSX build the vsix? If it's simply run `vsce package`, then I'm afraid it will cause some problem.

**Comment by amvanbaren** [comment]
@jdneo `ovsx`, the Open VSX CLI, calls `vsce`'s `createVSIX` function. https://github.com/eclipse/openvsx/blob/f013e2d8ec9e4e4cc4b9fdc14980c2d59584cc66/cli/src/publish.ts#L163

Is `ovsx` missing functionality or does `vscode-java-dependency` have extra (non standard) build steps?

**Comment by amvanbaren** [comment]
Ok, in that case `ovsx` also supports publishing pre-built VSIX packages:
```
npx ovsx publish --packagePath 'path/to/package.vsix' -p my-access-token
```

**Comment by amvanbaren** [comment]
> Ok, in that case `ovsx` also supports publishing pre-built VSIX packages:
> 
> ```
> npx ovsx publish --packagePath 'path/to/package.vsix' -p my-access-token
> ```

To clarify, you build the VSIX package and  publish it to the Visual Studio Marketplace, and then publish the same package to the Open VSX Registry using the above command.

**Comment by jdneo** [comment]
@amvanbaren We didn't release the vsix to Open VSX Registry, and I don't know who did those releases before either. Given that the limited resources we have, at least in the near future, we will only maintain the release in the VS Code Marketplace.

**Comment by filiptronicek** [comment]
Thanks for the assistance here, @jdneo! 

I am currently responsible for releasing the extension to Open VSX and therefore, if you get any other reports concerning the version published there feel free to ping me anywhere :).

We are currently in the process of removing the broken version of 0.23.0 and re-publishing it with https://github.com/microsoft/vscode-java-dependency/releases/download/0.23.0/vscjava.vscode-java-dependency-0.23.0.vsix.

**Comment by jdneo** [comment]
@filiptronicek Thank you for the help!

**Comment by TechPro424** [comment]
Is the issue supposed to be fixed? I'm still having this issue

**Comment by TechPro424** [comment]
Oh just realised I'm supposed to ping @filiptronicek because the issue is closed meaning notifications may not go through
