### ISSUE TITLE
Icon theme for Java project

### ISSUE THREAD

**Issue by Lucas3oo** [microsoft/vscode-java-dependency#768]
Hi

I am working on a "product icon theme" to also include the icons used in this extension.

I notice that some of the icons (characters) also have colors like th one for java class and interface. The ones "symbol-class" and "symbol-interface". Which color properties are used for those? I want to change from organic and blue to say green and purple. If the other icons can have a custom color that would be great too.

I also notice that the same character is used for both a source folder and a module/jar under the JRE container. Namely "file-submodule". For theme purposes it would be nice if two different characters was used, e.g "file-module" and "file-submodule"

Tx /Lucas

**Comment by jdneo** [comment]
Hi @Lucas3oo,

All the icons used in this extension comes from https://github.com/microsoft/vscode-codicons.

The extension just provide the icons name to VS Code. I guess it's VS Code to determine the color of the icon according to the current theme (maybe)?

Hope this answers your question.

**Comment by Lucas3oo** [comment]
Yeah, thanks. 
I found that I could override some of the colors but not for all of them.
E.g. "symbolIcon.classForeground": "#4A8854", is possible but not "project", "zip-file" etc since that doesn't exists.

**Comment by jdneo** [comment]
Thanks for the update. The follow-up question, maybe you can try asking this question to vscode-codicons repo.
