### ISSUE TITLE
Create new class and package from explorer

### ISSUE THREAD

**Issue by btstream** [microsoft/vscode-java-dependency#78]
Is it possible to add a context menu for functions such as `new class` and `new package`?

**Comment by andxu** [comment]
Thanks for the advice, we are plan to add it.

**Comment by nistvan86** [comment]
What is the status on this?

In my opinion the dependencies view is the closest to what most Java developer is used to navigating the project in classic IDEs. So it would be a very important feature to be able to create packages and new classes in this view.

(Also refactor move operations for classes and packages could be initiated from this view by dragging and dropping, but I can open a new request for that.)
