### ISSUE TITLE
Auto reveal in java project view sometimes don't work

### ISSUE THREAD

**Issue by xzbdmw** [microsoft/vscode-java-dependency#806]
There need to be a mauanally open in java project view command, Only "go to definition" in my source code file can auto reveal current file in java project view, other command such as workspace symbols search and "go to definition" in jdk source code file failed to auto reveal.

https://github.com/microsoft/vscode-java-dependency/assets/97848247/8b5bd8d1-5c8f-443a-bbf2-8df88d8c77dc

**Comment by xzbdmw** [comment]
mauanally unlink and link editor again solves this issue

**Comment by jdneo** [comment]
Is there any error in the server log? https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs

**Comment by xzbdmw** [comment]
seems no problem when I do a symbol search and auto reveal don't work

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-12-11 15:56:26.522
!MESSAGE >> java/validateDocument

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-12-11 15:56:26.935
!MESSAGE begin problem for /MMain.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-12-11 15:56:26.935
!MESSAGE 0 problems reported for /MMain.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-12-11 15:56:26.936
!MESSAGE Validated 1. Took 9 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-12-11 15:56:29.398
!MESSAGE >> java/validateDocument

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-12-11 15:56:29.809
!MESSAGE begin problem for /MMain.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-12-11 15:56:29.809
!MESSAGE 0 problems reported for /MMain.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-12-11 15:56:29.809
!MESSAGE Validated 1. Took 5 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-12-11 15:56:35.372
!MESSAGE >> java/validateDocument

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-12-11 15:56:35.783
!MESSAGE begin problem for /MMain.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-12-11 15:56:35.783
!MESSAGE 0 problems reported for /MMain.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-12-11 15:56:35.784
!MESSAGE Validated 1. Took 6 ms

**Comment by xzbdmw** [comment]
After switching to JDK17 problem solved
