### ISSUE TITLE
Java Projects view is not synced with editor when opening external libraries

### ISSUE THREAD

**Issue by mamilic** [microsoft/vscode-java-dependency#812]
[Screencast from 2024-01-10 14-30-12.webm](https://github.com/microsoft/vscode-java-dependency/assets/104531795/9eee2866-d4d9-4787-b9d2-242f1139eb5d)

When I try to navigate to Spring @PathVariable it does open the class file, however it is not synced with Java Projects view.

Steps:
1. Open demo project, which is attached(simple spring project) [demo.zip](https://github.com/microsoft/vscode-java-dependency/files/14664549/demo.zip)
2. Open Java Projects View
3. Open DemoApplication.java
4. Navigate to SpringApplication class by ctrl+Left Click
5. Java Projects View is not synced

However, Java projects view is working perfect with Java classes, and classes which are in the project.

**Comment by mamilic** [comment]
If you need any additional info regarding this bug, please let me know.

**Comment by jdneo** [comment]
Is this issue reproducible all the time? If yes, would be great if we have the steps.

**Comment by mamilic** [comment]
The issues is reproducible all the time, I;ve added the steps to the issue body.

**Comment by jdneo** [comment]
Thank you! I will take a look!

**Comment by mamilic** [comment]
The view is now synced. Closing the issue. Thanks @jdneo !
