### ISSUE TITLE
error by output by .jar

### ISSUE THREAD

**Issue by EfreetAria** [microsoft/vscode-java-dependency#819]
Error: No valid classpath found in the export jar configuration. Please make sure your configuration contains valid classpath(s).

why this error happened?
i changed computer,this problem only happened in specific computer

**Comment by EfreetAria** [comment]
![Uploading Snipaste_2024-02-21_23-25-35.png…]()
It can also happen on a new project

**Comment by EfreetAria** [comment]
i may find out the problem is in setting.json

"java.project.referencedLibraries": [
        "lib/**/*.jar"

 but my simple code don't have referenced lib,delete this will succed output.

**Comment by jdneo** [comment]
Close as the issue has been resolved.
