### ISSUE TITLE
The side bar keeps popping up when a new Java file opens

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode-java-dependency#83]
- Open a java file in a java project 
- close the side bar (`cmd+b` on mac)
- navigate to a new file from the same project
- side bar pops up
- repeat ...

This is **extremely** irritating  when trying to step debugging into another file, the debug view is replaced by the explorer. Also looks bad when performing a live demo with limited screen real estate.

Dependency view sync with opened files should only work when the side bar is visible.

**Comment by andxu** [comment]
good idea, i will implement a solution.
