### ISSUE TITLE
Package lombok does not exist(compiler.err.doesnt.exist)

### ISSUE THREAD

**Issue by JinghuaOriental** [microsoft/vscode-java-dependency#837]
It shows the jar package I imported doesn't exist, maybe the way I import is not correct?
I import the external jar package by "JAVA PROJECTS" -> "Referenced Libraries" -> "+" to add my jar package path. Then it appears in the Referenced Libraries.

See the jar package "lombok" as follow.
![image](https://github.com/microsoft/vscode-java-dependency/assets/87650189/80edf36e-a02a-406b-9fe2-a9c25ed0f536)
![image](https://github.com/microsoft/vscode-java-dependency/assets/87650189/045da9a4-1d19-4563-be41-c6d6b73ab117)

The background is I use vscode ssh in Windows to connect remote ubuntu server. And it doesn't show this problem when I develop on local.
Although this problem appear, I debug the code it can normally run. While I directly run the code it shows the problems mentioned earlier.

**Comment by JinghuaOriental** [comment]
> Have you installed other Java related extension? Looks like the error is not reported by us.

![image](https://github.com/microsoft/vscode-java-dependency/assets/87650189/372858ab-643d-4194-8af0-98b67e535276)
I have installed the "Extension Pack for Java" in the remote server, do I need install other Java related extensions?

**Comment by jdneo** [comment]
I believe this is reported by the second extension `Java`, which is published by Oracle.

**Comment by cypher256** [comment]
@JinghuaOriental Try disabling or uninstalling the following extension
[Java Language Support](https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac) George Fraser

**Comment by JinghuaOriental** [comment]
Sorry, now I meet the [new problem](https://github.com/microsoft/vscode-java-dependency/issues/838#issue-2339570758)...
So I have to fix the problem of adding jar package first.

**Comment by JinghuaOriental** [comment]
Now I have **replace the jar package with another version**, then it works.
It's so painful, I still don't know why.
**Anyway, thanks for all of you.**
