### ISSUE TITLE
"JAVA DEPENDENCIES" View should always show

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-java-dependency#92]
### Current Behavior
Currently, the view only shows up when the Java LS finishes loading the project.

### Expected Behavior

- The view needs to be statically showing in the file explorer view. Its visibility should be controlled by users.
- When the view is loading and has nothing to show, show icon or text to indicate the loading status just like other views.

**Comment by yaohaizh** [comment]
Tried different combination, logged an issue for this: 
https://github.com/redhat-developer/vscode-java/issues/888
