### ISSUE TITLE
The class which has no source can't show the substructure

### ISSUE THREAD

**Issue by lxhmavis** [Microsoft/vscode-java-dependency#95]
OS: Windows
Configurations: Vscode 1.29.0&&JDK1.8.0_191

Sample project:
[simple.zip](https://github.com/Microsoft/vscode-java-dependency/files/2579961/simple.zip)

When I open the class in the jar,I can't see its substructure, the behavior has below:
![image](https://user-images.githubusercontent.com/41565966/48464230-cca51f00-e819-11e8-9610-3d7beae2b9b7.png)

**Comment by andxu** [comment]
Dup as https://github.com/Microsoft/vscode-java-dependency/pull/105
