### ISSUE TITLE
There is no order about the substructure of string class

### ISSUE THREAD

**Issue by lxhmavis** [Microsoft/vscode-java-dependency#97]
OS: Windows
Configurations: Vscode1.29.0&&JDK1.8.0_191

When I open the substructure of the string class, It is shown as below: 
I think it could be sorted as alphabetical order.
![image](https://user-images.githubusercontent.com/41565966/48468649-7048fc00-e827-11e8-9260-c84208253f93.png)

**Comment by jdneo** [comment]
The list order here is the order of occurrence in the class, which is a kind of valid order.

What we need to think about is whether we need to add another kind of sorted order for the users. I'll close this issue and create another one.
